// Lückentexte: ein Satz zu einer Bibelstelle mit einer Lücke („___“). Alle erfinden, was hineingehört;
// die Wahrheit steht wie gewohnt anonym zwischen den Bluffs. Die Sätze sind mit eigenen Worten
// formuliert, ohne geschützte Bibelübersetzungen zu zitieren.
//
// Wie bei den Fragen (questions.ts): answer, variants und bluffs sind Satzteile, die grammatisch in
// die Lücke passen; accept fängt Bluffs ab, die der Wahrheit zu nah kommen. Dazu gehört zu jedem
// Lückentext ein Spickzettel fürs Gespräch (GAP_TALK).

import type { TalkNotes } from '../shared/types';
import type { Question } from './questions';

export const GAP_QUESTIONS: Question[] = [
  // ───────────── Altes Testament ─────────────
  {
    id: 'lt-simson',
    kind: 'gap',
    book: 'Richter',
    group: 'at',
    difficulty: 2,
    prompt: 'Simson erschlug tausend Philister mit ___.',
    answer: 'dem Kieferknochen eines Esels',
    variants: ['dem Kinnbacken eines Esels', 'einem Eselskinnbacken', 'einem Eselskiefer'],
    accept: [['kiefer'], ['*kinnback'], ['*kinnlad'], ['*eselskiefer'], ['*knochen', '*esel']],
    bluffs: ['einem Ochsenstachel', 'einem Zeltpflock', 'einer Steinschleuder'],
    ref: 'Richter 15,14–17',
    discovery:
      'Danach dichtete Simson ein Siegeslied mit Wortspiel: Im Hebräischen klingen „Esel“ und „Haufen“ fast gleich. Den Ort nannte man Ramat-Lehi, „Kieferhöhe“.',
  },
  {
    id: 'lt-steine',
    kind: 'gap',
    book: '1. Samuel',
    group: 'at',
    difficulty: 1,
    prompt: 'Für den Kampf gegen Goliat las David ___ aus dem Bach auf.',
    answer: 'fünf glatte Steine',
    variants: ['fünf Steine', 'fünf Kieselsteine'],
    accept: [['=fuenf', '*stein'], ['=5', '*stein'], ['=fuenf', '*kiesel'], ['=5', '*kiesel']],
    bluffs: ['drei scharfkantige Steine', 'sieben runde Kiesel', 'zwölf Steine für die zwölf Stämme'],
    ref: '1. Samuel 17,38–40',
    discovery: 'Er steckte sie in seine Hirtentasche. Gebraucht hat er nur einen einzigen: Der Stein traf Goliat an der Stirn (1. Samuel 17,49).',
    number: true,
  },
  {
    id: 'lt-taube',
    kind: 'gap',
    book: '1. Mose',
    group: 'at',
    difficulty: 1,
    prompt: 'Beim zweiten Flug kam die Taube am Abend zur Arche zurück – mit ___ im Schnabel.',
    answer: 'einem frischen Ölblatt',
    variants: ['einem Olivenblatt', 'einem Ölzweig', 'einem Olivenzweig'],
    accept: [['*oelblatt'], ['*oelzweig'], ['*oelbaum'], ['*oliv']],
    bluffs: ['einer Weinranke', 'einer Weizenähre', 'einem Zweig vom Zedernbaum'],
    ref: '1. Mose 8,8–12',
    discovery: 'Daran erkannte Noah, dass das Wasser gesunken war. Eine Woche später ließ er sie noch einmal fliegen – diesmal kam sie nicht wieder.',
  },
  {
    id: 'lt-jona',
    kind: 'gap',
    book: 'Jona',
    group: 'at',
    difficulty: 1,
    prompt: 'Jona war ___ im Bauch des großen Fisches.',
    answer: 'drei Tage und drei Nächte',
    variants: ['drei Tage'],
    accept: [['=drei', 'tag'], ['=3', 'tag'], ['=drei', '*naecht'], ['=3', '*naecht']],
    bluffs: ['sieben Tage und sieben Nächte', 'vierzig Tage lang', 'einen Tag und eine Nacht'],
    ref: 'Jona 2,1–11',
    discovery: 'Jesus greift das später auf: Wie Jona drei Tage im Fisch war, so werde der Menschensohn drei Tage im Schoß der Erde sein (Matthäus 12,40).',
    number: true,
  },
  {
    id: 'lt-loewengrube',
    kind: 'gap',
    book: 'Daniel',
    group: 'at',
    difficulty: 1,
    prompt: 'Daniel erklärte dem König, warum ihm die Löwen nichts getan hatten: Gott hatte ___ geschickt.',
    answer: 'seinen Engel',
    variants: ['einen Engel'],
    accept: [['engel'], ['=bote'], ['*cherub'], ['*seraph']],
    bluffs: ['einen Schutzwall aus Feuer', 'eine Wolke voller Licht', 'einen tiefen Schlaf über die Löwen'],
    ref: 'Daniel 6,17–24',
    discovery: 'König Darius hatte die ganze Nacht nicht geschlafen. Am Morgen eilte er zur Grube und fand Daniel unverletzt – weil er seinem Gott vertraut hatte (Daniel 6,19–24).',
  },
  {
    id: 'lt-gideon',
    kind: 'gap',
    book: 'Richter',
    group: 'at',
    difficulty: 2,
    prompt: 'Gideon zog am Ende mit nur ___ gegen das Heer der Midianiter.',
    answer: 'dreihundert Mann',
    variants: ['300 Mann', '300 Männern'],
    accept: [['dreihundert'], ['=300']],
    bluffs: ['siebzig Mann', 'dreitausend Mann', 'zwölf Mann aus jedem Stamm'],
    ref: 'Richter 7,2–8',
    discovery: 'Ausgewählt wurden die, die das Wasser mit der Hand zum Mund führten und leckten wie ein Hund. Israel sollte den Sieg nicht der eigenen Stärke zuschreiben (Richter 7,2).',
    number: true,
  },
  {
    id: 'lt-leiter',
    kind: 'gap',
    book: '1. Mose',
    group: 'at',
    difficulty: 1,
    prompt: 'In Bethel träumte Jakob von ___, auf der Engel hinauf- und hinabstiegen.',
    answer: 'einer Leiter',
    variants: ['einer Treppe', 'einer Himmelsleiter'],
    accept: [['*leiter'], ['*treppe'], ['*stufen']],
    bluffs: ['einer goldenen Brücke', 'einer Säule aus Feuer', 'einer Straße aus Wolken'],
    ref: '1. Mose 28,10–19',
    discovery: 'Jakob war auf der Flucht vor seinem Bruder Esau und schlief mit einem Stein unter dem Kopf. Den Ort nannte er danach Bethel – „Haus Gottes“.',
  },
  {
    id: 'lt-karmel',
    kind: 'gap',
    book: '1. Könige',
    group: 'at',
    difficulty: 2,
    prompt: 'Bevor Elia auf dem Karmel um Feuer betete, ließ er Opfer und Holz ___ übergießen.',
    answer: 'dreimal mit Wasser',
    variants: ['mit Wasser', 'mit zwölf Krügen Wasser'],
    accept: [['*wasser']],
    bluffs: ['mit Lampenöl', 'mit Wein und Honig', 'mit dem Blut eines Widders'],
    ref: '1. Könige 18,30–39',
    discovery: 'Er ließ sogar einen Graben um den Altar ausheben, bis auch der voll Wasser stand. Dann fiel das Feuer und verzehrte Opfer, Holz, Steine – und das Wasser im Graben.',
  },
  {
    id: 'lt-jericho',
    kind: 'gap',
    book: 'Josua',
    group: 'at',
    difficulty: 1,
    prompt: 'Am siebten Tag zogen die Israeliten ___ um Jericho, dann stürzte die Mauer ein.',
    answer: 'siebenmal',
    variants: ['sieben Mal', 'sieben Runden'],
    accept: [['siebenmal'], ['=sieben'], ['=7'], ['=7mal']],
    bluffs: ['dreimal', 'zwölfmal', 'vierzigmal'],
    ref: 'Josua 6,12–20',
    discovery: 'Sechs Tage lang waren sie jeweils einmal schweigend um die Stadt gezogen. Am siebten Tag bliesen die Priester die Hörner, alle schrien laut – und die Mauer fiel.',
    number: true,
  },
  {
    id: 'lt-dornbusch',
    kind: 'gap',
    book: '2. Mose',
    group: 'at',
    difficulty: 1,
    prompt: 'Am brennenden Dornbusch sollte Mose ___, denn der Ort war heiliger Boden.',
    answer: 'seine Schuhe ausziehen',
    variants: ['die Sandalen ausziehen', 'barfuß gehen'],
    accept: [['*schuh'], ['*sandal'], ['*barfuss']],
    bluffs: ['seinen Hirtenstab ablegen', 'sich siebenmal verneigen', 'seine Hände waschen'],
    ref: '2. Mose 3,1–6',
    discovery: 'Der Busch brannte, ohne zu verbrennen. Mose hütete gerade die Schafe seines Schwiegervaters Jitro – mit rund 80 Jahren begann für ihn ein ganz neuer Auftrag.',
  },

  // ───────────── Evangelien ─────────────
  {
    id: 'lt-senfkorn',
    kind: 'gap',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Das Himmelreich gleicht ___: Es wird so groß, dass die Vögel in seinen Zweigen nisten.',
    answer: 'einem Senfkorn',
    variants: ['einem Senfsamen'],
    accept: [['*senf']],
    bluffs: ['einem Dattelkern', 'einem Weizenkorn', 'einem Zedernsamen'],
    ref: 'Matthäus 13,31–32',
    discovery: 'Ausgerechnet eines der kleinsten Samenkörner wird zu einer großen Staude. Gottes Reich beginnt unscheinbar – und wird größer, als man denkt.',
  },
  {
    id: 'lt-brot-allein',
    kind: 'gap',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Jesus antwortet dem Versucher: Der Mensch lebt nicht vom Brot allein, sondern von ___.',
    answer: 'jedem Wort aus Gottes Mund',
    variants: ['jedem Wort Gottes', 'Gottes Wort'],
    accept: [['*wort']],
    bluffs: ['der Hoffnung auf Gottes Reich', 'der Liebe seiner Nächsten', 'dem Wasser des Lebens'],
    ref: 'Matthäus 4,1–4',
    discovery: 'Jesus antwortet mit einem Satz aus 5. Mose 8,3. Dort erinnert Mose Israel an das Manna in der Wüste: Gott versorgt – und er spricht.',
  },
  {
    id: 'lt-petrus-wind',
    kind: 'gap',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Petrus ging auf dem Wasser auf Jesus zu – bis er ___ sah und Angst bekam.',
    answer: 'den starken Wind',
    variants: ['den Wind', 'den Sturm'],
    accept: [['*wind'], ['*sturm'], ['*boe']],
    bluffs: ['die Tiefe unter seinen Füßen', 'einen großen Fisch unter sich', 'die anderen Jünger lachen'],
    ref: 'Matthäus 14,28–31',
    discovery: 'Als er sank, schrie er: Herr, rette mich! Jesus griff sofort nach ihm – und fragte: Warum hast du gezweifelt?',
  },
  {
    id: 'lt-menschenfischer',
    kind: 'gap',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Jesus sagte zu Simon und Andreas: Kommt, folgt mir nach! Ich will euch zu ___ machen.',
    answer: 'Menschenfischern',
    variants: ['Fischern von Menschen'],
    accept: [['menschenfisch'], ['*fischer']],
    bluffs: ['Hirten meiner Herde', 'Arbeitern in meinem Weinberg', 'Boten des Königs'],
    ref: 'Markus 1,16–18',
    discovery: 'Sie ließen ihre Netze sofort liegen. „Sofort“ ist ein Lieblingswort des Markus – es steht über 40-mal in seinem kurzen Evangelium.',
  },
  {
    id: 'lt-witwe',
    kind: 'gap',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Die arme Witwe warf ___ in den Opferkasten – und gab damit mehr als alle anderen.',
    answer: 'zwei kleine Münzen',
    variants: ['zwei Scherflein', 'zwei Lepta', 'zwei Kupfermünzen'],
    accept: [['*muenz', '=zwei'], ['*muenz', '=2'], ['scherf'], ['*lepta'], ['*lepton']],
    bluffs: ['ihren Ehering', 'einen Silbergroschen', 'eine Handvoll Gerste'],
    ref: 'Markus 12,41–44',
    discovery: 'Zusammen waren sie einen Quadrans wert, fast nichts. Jesus sagt: Die anderen gaben von ihrem Überfluss, sie gab alles, was sie zum Leben hatte.',
  },
  {
    id: 'lt-krippe',
    kind: 'gap',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Maria legte ihr Kind in ___, weil im Gästeraum kein Platz für sie war.',
    answer: 'eine Futterkrippe',
    variants: ['eine Krippe', 'einen Futtertrog'],
    accept: [['*krippe'], ['*trog']],
    bluffs: ['einen Weidenkorb', 'eine Satteltasche', 'ein Bett aus Stroh'],
    ref: 'Lukas 2,6–7',
    discovery: 'Die Krippe wird für die Hirten zum Erkennungszeichen: ein Kind in Windeln, in einem Futtertrog – so finden sie den Retter (Lukas 2,12).',
  },
  {
    id: 'lt-lebensbrot',
    kind: 'gap',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Jesus sagt: Ich bin ___. Wer zu mir kommt, wird nie mehr hungern.',
    answer: 'das Brot des Lebens',
    variants: ['das Lebensbrot', 'das Brot'],
    accept: [['*brot']],
    bluffs: ['die Quelle der Kraft', 'der Fels in der Wüste', 'der Krug, der nie leer wird'],
    ref: 'Johannes 6,35',
    discovery: 'Jesus sagt das am Tag nach der Speisung der Fünftausend. Viele suchten ihn nur wegen des nächsten Brotwunders – er bietet sich selbst an (Johannes 6,26).',
  },
  {
    id: 'lt-nadeloehr',
    kind: 'gap',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Eher geht ___ durch ein Nadelöhr, als dass ein Reicher in das Reich Gottes kommt.',
    answer: 'ein Kamel',
    accept: [['kamel']],
    bluffs: ['ein Ochse', 'ein Elefant', 'ein beladener Esel'],
    ref: 'Markus 10,23–27',
    discovery: 'Die Jünger erschrecken: Wer kann dann gerettet werden? Jesus antwortet: Bei Menschen ist es unmöglich, aber nicht bei Gott.',
  },
  {
    id: 'lt-aussaetzige',
    kind: 'gap',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Von zehn geheilten Aussätzigen kam nur ___ zurück, um Jesus zu danken.',
    answer: 'ein Samariter',
    variants: ['einer', 'ein Einziger'],
    accept: [['samarit'], ['=einer'], ['=1'], ['*einzig']],
    bluffs: ['ein Zöllner aus Jericho', 'ein römischer Soldat', 'ein junger Hirte'],
    ref: 'Lukas 17,11–19',
    discovery: 'Ausgerechnet der Fremde kehrt um und dankt. Jesus sagt zu ihm: Steh auf und geh – dein Glaube hat dich gerettet.',
  },
  {
    id: 'lt-johannes-316',
    kind: 'gap',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'So sehr hat Gott die Welt geliebt, dass er ___ gab.',
    answer: 'seinen einzigen Sohn',
    variants: ['seinen Sohn', 'seinen eingeborenen Sohn'],
    accept: [['*sohn']],
    bluffs: ['sein ganzes Königreich', 'den Menschen sein Gesetz', 'seinen Thron im Himmel'],
    ref: 'Johannes 3,16',
    discovery: 'Der Satz steht mitten im nächtlichen Gespräch mit Nikodemus. Gleich danach heißt es: Gott hat den Sohn nicht gesandt, um die Welt zu richten, sondern um sie zu retten (3,17).',
  },
  {
    id: 'lt-peitsche',
    kind: 'gap',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Im Tempel machte Jesus eine Peitsche aus ___ und trieb die Händler hinaus.',
    answer: 'Stricken',
    variants: ['Schnüren', 'Seilen', 'Kordeln'],
    accept: [['*strick'], ['*seil'], ['*schnur'], ['*schnuer'], ['*kordel']],
    bluffs: ['Lederriemen', 'Palmzweigen', 'Weidenruten'],
    ref: 'Johannes 2,13–17',
    discovery: 'Nur Johannes erwähnt die selbst gemachte Peitsche. Den Jüngern kam dabei ein Psalmwort über den brennenden Eifer für Gottes Haus in den Sinn (Psalm 69,10).',
  },
  {
    id: 'lt-kana',
    kind: 'gap',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Bei der Hochzeit in Kana sagte ___ zu den Dienern: Was er euch sagt, das tut!',
    answer: 'Maria, die Mutter Jesu',
    variants: ['Maria', 'seine Mutter', 'die Mutter Jesu'],
    accept: [['maria'], ['*mutter']],
    bluffs: ['der Speisemeister', 'der Bräutigam', 'Petrus'],
    ref: 'Johannes 2,1–5',
    discovery: 'Es sind ihre letzten Worte im Johannesevangelium. Danach verwandelt Jesus Wasser in Wein – das erste seiner Zeichen.',
  },

  // ───────────── Apostelgeschichte ─────────────
  {
    id: 'lt-pfingsten',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 1,
    prompt: 'An Pfingsten erschienen über den Jüngern ___, die sich auf jeden von ihnen setzten.',
    answer: 'Zungen wie von Feuer',
    variants: ['Feuerzungen', 'Flammen', 'Zungen aus Feuer'],
    accept: [['*zunge'], ['*feuer'], ['*flamm']],
    bluffs: ['weiße Tauben', 'leuchtende Sterne', 'goldene Kronen'],
    ref: 'Apostelgeschichte 2,1–4',
    discovery: 'Dazu kam ein Brausen wie von einem gewaltigen Sturm. Pilger aus vielen Ländern hörten die Jünger von Gottes großen Taten reden – jeder in seiner eigenen Sprache.',
  },
  {
    id: 'lt-stephanus',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Kurz vor seinem Tod sah Stephanus den Himmel offen und ___ zur Rechten Gottes stehen.',
    answer: 'Jesus',
    variants: ['den Menschensohn', 'Christus'],
    accept: [['jesus'], ['*menschensohn'], ['christus'], ['=sohn']],
    bluffs: ['den Erzengel Michael', 'Mose und Elia', 'einen Engel mit Flammenschwert'],
    ref: 'Apostelgeschichte 7,54–60',
    discovery: 'Sonst heißt es, Christus sitze zur Rechten Gottes. Hier steht er – viele Ausleger sehen darin, dass er sich für seinen Zeugen erhebt.',
  },
  {
    id: 'lt-kaemmerer',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Der Finanzminister aus Äthiopien las auf seinem Wagen laut im Buch ___.',
    answer: 'des Propheten Jesaja',
    variants: ['Jesaja'],
    accept: [['jesaja']],
    bluffs: ['des Propheten Daniel', 'der Psalmen Davids', 'der Sprüche Salomos'],
    ref: 'Apostelgeschichte 8,26–35',
    discovery: 'Er las gerade vom Lamm, das zur Schlachtbank geführt wird (Jesaja 53). Philippus fragte: Verstehst du, was du liest? – und erzählte ihm von dort aus von Jesus.',
  },
  {
    id: 'lt-malta',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Auf Malta hängte sich ___ an die Hand von Paulus, doch er schüttelte das Tier einfach ins Feuer.',
    answer: 'eine giftige Schlange',
    variants: ['eine Schlange', 'eine Viper', 'eine Otter'],
    accept: [['*schlang'], ['*viper'], ['*otter'], ['*natter']],
    bluffs: ['ein großer Skorpion', 'eine Ratte aus dem Schiffsbauch', 'ein wütender Affe'],
    ref: 'Apostelgeschichte 28,1–6',
    discovery: 'Die Inselbewohner hielten ihn zuerst für einen Mörder, den die Strafe nun doch einholt. Als ihm nichts geschah, hielten sie ihn für einen Gott.',
  },
  {
    id: 'lt-damaskus',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Nach der Begegnung mit Jesus vor Damaskus war Saulus ___ blind und aß und trank nichts.',
    answer: 'drei Tage lang',
    variants: ['drei Tage'],
    accept: [['=drei', 'tag'], ['=3', 'tag']],
    bluffs: ['sieben Tage lang', 'vierzig Tage lang', 'einen ganzen Monat lang'],
    ref: 'Apostelgeschichte 9,1–9',
    discovery: 'Dann schickte Gott ausgerechnet Hananias zu ihm, der Angst vor dem Verfolger hatte. Als er ihm die Hände auflegte, fiel es Saulus wie Schuppen von den Augen – daher kommt die Redewendung.',
    number: true,
  },
  {
    id: 'lt-gamaliel',
    kind: 'gap',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 3,
    prompt: 'Der Pharisäer Gamaliel riet dem Hohen Rat, die Apostel ___ – sei ihr Werk von Gott, könne man es ohnehin nicht aufhalten.',
    answer: 'in Ruhe zu lassen',
    variants: ['gewähren zu lassen', 'laufen zu lassen', 'freizulassen'],
    accept: [['*ruhe'], ['*gewaehren'], ['=laufen'], ['*freizulassen'], ['*freilass'], ['*loszulassen'], ['*loslass']],
    bluffs: ['nach Rom zu schicken', 'aus der Stadt zu verbannen', 'ins Gefängnis zu werfen'],
    ref: 'Apostelgeschichte 5,33–40',
    discovery: 'Er erinnerte an zwei frühere Bewegungen, die im Sand verlaufen waren. Gamaliel war übrigens der Lehrer von Paulus (Apostelgeschichte 22,3).',
  },

  // ───────────── Paulusbriefe ─────────────
  {
    id: 'lt-zum-besten',
    kind: 'gap',
    book: 'Römer',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Wir wissen: Denen, die Gott lieben, dienen ___ zum Besten.',
    answer: 'alle Dinge',
    variants: ['alles'],
    accept: [['=alles'], ['=alle', '*ding'], ['*saemtlich']],
    bluffs: ['die schweren Zeiten', 'Gottes Gebote', 'Gebet und Fasten'],
    ref: 'Römer 8,28',
    discovery: 'Paulus sagt nicht, dass alles gut ist – sondern dass Gott selbst Schweres zum Guten wenden kann. Kurz danach folgt: Nichts kann uns von Gottes Liebe trennen (8,38–39).',
  },
  {
    id: 'lt-die-groesste',
    kind: 'gap',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Nun bleiben Glaube, Hoffnung, Liebe, diese drei – aber ___ ist die größte unter ihnen.',
    answer: 'die Liebe',
    accept: [['liebe']],
    bluffs: ['die Hoffnung', 'die Wahrheit', 'die Demut'],
    ref: '1. Korinther 13,13',
    discovery: 'Glaube wird einmal zum Schauen und Hoffnung zur Erfüllung. Die Liebe aber hört niemals auf (1. Korinther 13,8).',
  },
  {
    id: 'lt-aus-gnade',
    kind: 'gap',
    book: 'Epheser',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Aus Gnade seid ihr gerettet durch ___ – und das nicht aus euch selbst: Gottes Geschenk ist es.',
    answer: 'den Glauben',
    variants: ['Glauben'],
    accept: [['glaube']],
    bluffs: ['die Taufe', 'gute Werke', 'das Gebet'],
    ref: 'Epheser 2,8–10',
    discovery: 'Gleich danach heißt es: Wir sind Gottes Werk, geschaffen zu guten Werken. Gute Taten sind nicht der Weg zur Rettung, sondern ihre Folge.',
  },
  {
    id: 'lt-freut-euch',
    kind: 'gap',
    book: 'Philipper',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Freut euch im Herrn ___! Und noch einmal sage ich: Freut euch!',
    answer: 'allezeit',
    variants: ['zu jeder Zeit', 'immer', 'jederzeit'],
    accept: [['allezeit'], ['allewege'], ['*jederzeit'], ['=immer'], ['=jeder', 'zeit'], ['=stets']],
    bluffs: ['in der Gemeinde', 'am Tag des Herrn', 'mit Psalmen und Liedern'],
    ref: 'Philipper 4,4–7',
    discovery: 'Paulus schreibt das aus der Haft. Freude ist ein Leitwort des ganzen Briefes – das Wortfeld kommt darin mehr als ein Dutzend Mal vor.',
  },
  {
    id: 'lt-pruefet',
    kind: 'gap',
    book: '1. Thessalonicher',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Prüft alles und ___!',
    answer: 'behaltet das Gute',
    variants: ['das Gute behaltet', 'behaltet, was gut ist'],
    accept: [['*gut', '*halt'], ['=gute'], ['=guten']],
    bluffs: ['verwerft das Fremde', 'betet ohne Unterlass', 'fragt eure Ältesten'],
    ref: '1. Thessalonicher 5,19–22',
    discovery: 'Davor mahnt Paulus, den Geist nicht auszulöschen, danach, das Böse in jeder Form zu meiden: Prophetie soll man nicht verachten, aber prüfen.',
  },
  {
    id: 'lt-schrift',
    kind: 'gap',
    book: '2. Timotheus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Alle Schrift ist ___ und nützlich zur Lehre, zur Zurechtweisung und zur Erziehung.',
    answer: 'von Gott eingegeben',
    variants: ['gottgehaucht', 'von Gott inspiriert', 'von Gott eingehaucht'],
    accept: [['*eingegeb'], ['*gehaucht'], ['*inspir'], ['gott'], ['goettlich']],
    bluffs: ['uralt und ehrwürdig', 'sorgfältig abgeschrieben', 'von Mose überliefert'],
    ref: '2. Timotheus 3,14–17',
    discovery: 'Das griechische Wort theopneustos heißt wörtlich „gottgehaucht“. Gemeint waren zuerst die heiligen Schriften, die Timotheus seit seiner Kindheit kannte – unser Altes Testament.',
  },
  {
    id: 'lt-mitweinen',
    kind: 'gap',
    book: 'Römer',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Freut euch mit den Fröhlichen und ___!',
    answer: 'weint mit den Weinenden',
    variants: ['weint mit denen, die weinen'],
    accept: [['*wein']],
    bluffs: ['tröstet die Traurigen', 'betet für die Kranken', 'teilt mit den Armen'],
    ref: 'Römer 12,9–16',
    discovery: 'Johannes Chrysostomus meinte um 400, das Mitfreuen sei schwerer als das Mitweinen: Dabei stehe einem oft der Neid im Weg.',
  },

  // ───────────── Weitere Briefe ─────────────
  {
    id: 'lt-nicht-sieht',
    kind: 'gap',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Glaube heißt: fest mit dem rechnen, was man hofft, und nicht zweifeln an dem, was ___.',
    answer: 'man nicht sieht',
    variants: ['unsichtbar ist', 'man nicht sehen kann'],
    accept: [['=sieht'], ['=sehen'], ['*unsichtbar']],
    bluffs: ['die Väter gelehrt haben', 'die Propheten verkündigt haben', 'man im Herzen spürt'],
    ref: 'Hebräer 11,1',
    discovery: 'Danach folgt eine lange Reihe von Glaubensvorbildern – von Abel über Abraham bis Rahab. Viele von ihnen erlebten die Erfüllung selbst nicht mehr (Hebräer 11,13).',
  },
  {
    id: 'lt-langsam',
    kind: 'gap',
    book: 'Jakobus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Jeder Mensch sei schnell zum Hören, langsam zum Reden und langsam ___.',
    answer: 'zum Zorn',
    variants: ['zum Zornigwerden', 'zum Ärger'],
    accept: [['*zorn'], ['*wut'], ['*aerger']],
    bluffs: ['zum Urteilen', 'zum Klagen', 'zum Versprechen'],
    ref: 'Jakobus 1,19–20',
    discovery: 'Die Begründung folgt sofort: Menschlicher Zorn bewirkt nicht, was vor Gott gerecht ist.',
  },
  {
    id: 'lt-sorgen',
    kind: 'gap',
    book: '1. Petrus',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Werft alle eure Sorgen auf ihn, denn ___.',
    answer: 'er sorgt für euch',
    variants: ['er kümmert sich um euch'],
    accept: [['*sorgt'], ['*kuemmert'], ['*fuersorg']],
    bluffs: ['seine Last ist leicht', 'er kennt eure Namen', 'sein Arm ist stark'],
    ref: '1. Petrus 5,6–7',
    discovery: 'Gleich im nächsten Vers warnt Petrus: Seid nüchtern und wachsam – der Widersacher geht umher wie ein brüllender Löwe (5,8).',
  },
  {
    id: 'lt-furcht',
    kind: 'gap',
    book: '1. Johannes',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Furcht ist nicht in der Liebe, sondern die vollkommene Liebe ___.',
    answer: 'treibt die Furcht aus',
    variants: ['vertreibt die Furcht', 'treibt die Angst aus'],
    accept: [['*treib'], ['*verjag'], ['*furcht', '*weg']],
    bluffs: ['überwindet jeden Zweifel', 'deckt viele Sünden zu', 'kennt keine Grenzen'],
    ref: '1. Johannes 4,16–19',
    discovery: 'Johannes begründet das so: Wer Angst hat, rechnet mit Strafe. Wer Gottes Liebe kennt, muss dem Tag des Gerichts nicht mit Angst entgegensehen.',
  },
  {
    id: 'lt-derselbe',
    kind: 'gap',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Jesus Christus ist derselbe ___.',
    answer: 'gestern, heute und in Ewigkeit',
    variants: ['gestern und heute und in Ewigkeit'],
    accept: [['gestern'], ['*ewig']],
    bluffs: ['im Himmel wie auf Erden', 'für Juden und Griechen', 'in guten wie in schlechten Tagen'],
    ref: 'Hebräer 13,7–9',
    discovery: 'Der Satz steht mitten in Mahnungen, sich an die früheren Lehrer zu erinnern und sich nicht von fremden Lehren mitreißen zu lassen.',
  },

  // ───────────── Offenbarung ─────────────
  {
    id: 'lt-a-und-o',
    kind: 'gap',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 1,
    prompt: 'Gott spricht: Ich bin ___, der Anfang und das Ende.',
    answer: 'das A und das O',
    variants: ['das Alpha und das Omega', 'A und O'],
    accept: [['alpha'], ['omega'], ['=a', '=o']],
    bluffs: ['das Licht der Lichter', 'der Fels aller Zeiten', 'die Quelle und das Meer'],
    ref: 'Offenbarung 1,8',
    discovery: 'Alpha und Omega sind der erste und der letzte Buchstabe des griechischen Alphabets. Daher kommt unsere Redewendung „das A und O“.',
  },
  {
    id: 'lt-anklopfen',
    kind: 'gap',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 1,
    prompt: 'Christus sagt: Siehe, ich stehe vor der Tür und ___.',
    answer: 'klopfe an',
    variants: ['klopfe', 'poche an'],
    accept: [['*klopf'], ['*poch']],
    bluffs: ['warte auf dich', 'rufe deinen Namen', 'bringe Brot und Wein'],
    ref: 'Offenbarung 3,20',
    discovery: 'Das Wort gilt ausgerechnet Laodizea, der lauen Gemeinde. Wer öffnet, mit dem will Christus essen – eine Einladung zur Gemeinschaft.',
  },
  {
    id: 'lt-traenen',
    kind: 'gap',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 1,
    prompt: 'Gott wird ___ abwischen, und der Tod wird nicht mehr sein.',
    answer: 'alle Tränen von ihren Augen',
    variants: ['alle Tränen', 'jede Träne'],
    accept: [['*traene']],
    bluffs: ['allen Staub von ihren Füßen', 'jeden Schleier von ihren Augen', 'die Schuld von ihren Stirnen'],
    ref: 'Offenbarung 21,3–4',
    discovery: 'Das Bild stammt aus Jesaja 25,8: Gott wird den Tod verschlingen und die Tränen von allen Gesichtern abwischen.',
  },
  {
    id: 'lt-perlentor',
    kind: 'gap',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Im neuen Jerusalem ist jedes der zwölf Tore aus ___ gemacht.',
    answer: 'einer einzigen Perle',
    variants: ['einer Perle', 'Perlen'],
    accept: [['*perl']],
    bluffs: ['massivem Gold', 'einem einzigen Diamanten', 'weißem Elfenbein'],
    ref: 'Offenbarung 21,10–21',
    discovery: 'Gold gibt es trotzdem: Die Straße der Stadt ist aus reinem Gold, durchsichtig wie Glas. Daher kommt das „Perlentor“ als Bild für den Eingang zum Himmel.',
  },
  {
    id: 'lt-leuchter',
    kind: 'gap',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Johannes sah den Menschensohn mitten zwischen sieben goldenen ___.',
    answer: 'Leuchtern',
    variants: ['Lampen', 'Leuchter'],
    accept: [['*leuchter'], ['*lamp'], ['*kerze'], ['*menora']],
    bluffs: ['Thronen', 'Säulen', 'Weinstöcken'],
    ref: 'Offenbarung 1,12–20',
    discovery: 'Die Offenbarung löst das Bild selbst auf: Die sieben Leuchter sind die sieben Gemeinden, an die Johannes schreibt (1,20). Christus steht mitten unter ihnen.',
  },
];

export const GAP_TALK: Record<string, TalkNotes> = {
  'lt-simson': {
    background: 'Kurz zuvor hatten Männer aus Juda Simson gefesselt an die Philister ausgeliefert, weil sie Ärger fürchteten. Als der Geist des HERRN über ihn kam, rissen die Stricke wie angesengter Flachs (Richter 15,11–14).',
    question: 'Simson hatte enorme Kraft, aber wenig Selbstbeherrschung. Wo sind Gaben ohne Charakter gefährlich?',
    crossRef: { ref: 'Sprüche 16,32', note: 'Wer sich selbst beherrscht, ist stärker als einer, der Städte erobert – Stärke einmal ganz anders gemessen.' },
  },
  'lt-steine': {
    background: 'Saul wollte David seine eigene Rüstung leihen, doch David konnte darin kaum gehen und legte sie wieder ab. Er kämpfte mit dem, was er als Hirte kannte: Stab, Schleuder und Steine.',
    question: 'David kämpft nicht in Sauls Rüstung, sondern mit dem, was er kann. Was ist euer „Werkzeug“, das Gott gebrauchen will?',
    crossRef: { ref: 'Sacharja 4,6', note: 'Nicht durch Heer oder Kraft, sondern durch Gottes Geist – dasselbe Prinzip wie bei Davids Sieg über Goliat.' },
  },
  'lt-taube': {
    background: 'Vor der Taube hatte Noah einen Raben ausgeschickt, der hin- und herflog. Die Taube fand beim ersten Flug keinen Ort zum Ausruhen und kehrte in die Arche zurück (1. Mose 8,7–9).',
    question: 'Woran merkt ihr, dass nach einer schweren Zeit wieder Leben wächst – und wie geduldig wartet ihr darauf?',
    crossRef: { ref: 'Klagelieder 3,22-23', note: 'Gottes Güte ist nicht zu Ende, sie ist jeden Morgen neu – Hoffnung mitten in den Trümmern.' },
  },
  'lt-jona': {
    background: 'Im Fisch betet Jona einen Psalm voller Bilder aus anderen Psalmen: Fluten, Tiefe, der Tempel. Er endet mit dem Bekenntnis, dass die Rettung beim HERRN liegt (Jona 2,3–10).',
    question: 'Jona betet erst, als er ganz unten ist. Warum suchen wir Gott oft erst in der Not – und was ändert das?',
    crossRef: { ref: 'Psalm 130,1-2', note: 'Aus der Tiefe rufe ich zu dir – ein Gebet, das auch aus dem Bauch des Fisches stammen könnte.' },
  },
  'lt-loewengrube': {
    background: 'Daniels Gegner wussten, dass er dreimal am Tag am offenen Fenster Richtung Jerusalem betete. Genau daraus machten sie eine Falle – mit einem Gesetz, das nicht einmal der König aufheben konnte.',
    question: 'Daniel betet weiter wie immer, obwohl es gefährlich ist. Welche festen Gewohnheiten tragen euren Glauben?',
    crossRef: { ref: 'Hebräer 11,33', note: 'Der Hebräerbrief nennt Menschen, die durch Glauben den Löwen den Rachen stopften – ein Echo auf Daniel.' },
  },
  'lt-gideon': {
    background: 'Zuerst hatte Gideon 32.000 Mann. Wer Angst hatte, durfte heimgehen – 22.000 gingen. Von den übrigen 10.000 blieben nach der Probe am Wasser nur 300 (Richter 7,3–7).',
    question: 'Gott macht Gideons Heer bewusst klein. Wo erlebt ihr, dass Schwäche Raum für Gottes Wirken schafft?',
    crossRef: { ref: '2. Korinther 12,9', note: 'Gottes Kraft kommt gerade in der Schwachheit zur Vollendung – Paulus lernt, was Gideon erlebt hat.' },
  },
  'lt-leiter': {
    background: 'Jakob hatte seinen Vater getäuscht und sich den Segen erschlichen. Ausgerechnet auf der Flucht, allein und schuldig, verspricht Gott ihm: Ich bin mit dir und behüte dich (1. Mose 28,15).',
    question: 'Gott begegnet Jakob nicht, als er alles richtig gemacht hat, sondern auf der Flucht. Was sagt das über Gottes Gnade?',
    crossRef: { ref: 'Johannes 1,51', note: 'Jesus kündigt an, man werde Engel über dem Menschensohn auf- und niedersteigen sehen – er selbst verbindet Himmel und Erde.' },
  },
  'lt-karmel': {
    background: 'Drei Jahre Dürre lagen hinter Israel. Die Propheten Baals hatten vom Morgen bis Mittag gerufen und sich sogar geritzt – nichts geschah. Elia spottete: Vielleicht schläft euer Gott (1. Könige 18,26–29).',
    question: 'Elia fragt das Volk, wie lange es noch zwischen Gott und Baal schwanken will. Wo seid ihr innerlich unentschieden?',
    crossRef: { ref: 'Jakobus 5,17-18', note: 'Elia war ein Mensch wie wir, schreibt Jakobus – und doch hatte sein Gebet große Kraft.' },
  },
  'lt-jericho': {
    background: 'Die Kundschafterin Rahab hatte zuvor zwei Späher versteckt. Als die Mauer fiel, wurden sie und ihre Familie verschont: Ihr Haus lag in der Stadtmauer, ein rotes Seil hing im Fenster (Josua 2; 6,22–25).',
    question: 'Sechs Tage lang passiert scheinbar nichts. Wie geht ihr mit Zeiten um, in denen Gehorsam keinen sichtbaren Erfolg hat?',
    crossRef: { ref: 'Hebräer 11,30', note: 'Durch den Glauben fielen die Mauern Jerichos, nachdem Israel sieben Tage um sie herumgezogen war.' },
  },
  'lt-dornbusch': {
    background: 'Mose hatte viele Einwände: Wer bin ich? Wie heißt du? Sie werden mir nicht glauben. Ich kann nicht gut reden. Gott antwortet auf jeden – und gibt ihm Aaron zur Seite (2. Mose 3–4).',
    question: 'Mose findet viele Gründe, warum er nicht der Richtige ist. Welche Einwände habt ihr, wenn Gott euch etwas zutraut?',
    crossRef: { ref: 'Josua 5,15', note: 'Auch Josua soll vor Jericho seine Schuhe ausziehen – derselbe Auftrag eine Generation später.' },
  },
  'lt-senfkorn': {
    background: 'Senfstauden am See Genezareth können mannshoch werden. Die Vögel in den Zweigen erinnern an Bilder bei Hesekiel und Daniel, wo ein großer Baum vielen Völkern Schutz bietet (Hesekiel 17,23).',
    question: 'Wo seht ihr heute kleine, unscheinbare Anfänge, aus denen Gott etwas Großes wachsen lassen könnte?',
    crossRef: { ref: 'Sacharja 4,10', note: 'Wer verachtet den Tag der kleinen Anfänge? Gott freut sich an dem, was klein beginnt.' },
  },
  'lt-brot-allein': {
    background: 'Nach 40 Tagen Fasten setzt der Versucher genau beim Hunger an. Jesus antwortet auf alle drei Versuchungen mit Worten aus dem 5. Buch Mose – nicht mit einem Wunder.',
    question: 'Wovon „lebt“ ihr innerlich – und wie viel Raum bekommt Gottes Wort im Alltag wirklich?',
    crossRef: { ref: '5. Mose 8,3', note: 'Gott ließ Israel hungern und gab Manna, damit es lernt: Der Mensch lebt von allem, was Gott sagt.' },
  },
  'lt-petrus-wind': {
    background: 'Nur Matthäus erzählt, dass Petrus selbst aufs Wasser wollte. Markus und Johannes berichten, wie Jesus über den See kommt, aber ohne Petrus (Markus 6,45–52; Johannes 6,16–21).',
    question: 'Petrus wagt den Schritt aus dem Boot und sinkt dann doch. Was ist euch wichtiger: nie zu sinken oder es zu wagen?',
    crossRef: { ref: 'Jesaja 43,2', note: 'Wenn du durchs Wasser gehst, will ich bei dir sein, verspricht Gott – die Ströme sollen dich nicht fortreißen.' },
  },
  'lt-menschenfischer': {
    background: 'Jesus beruft die Fischer mitten bei der Arbeit, mit einem Bild aus ihrem eigenen Beruf. Schon in Jeremia 16,16 schickt Gott „Fischer“ aus, die Menschen einsammeln sollen.',
    question: 'Jesus knüpft an das an, was die Jünger können. Welche eurer Fähigkeiten könnte Gott in seinen Dienst nehmen?',
    crossRef: { ref: 'Lukas 5,10', note: 'Bei Lukas sagt Jesus zu Petrus: Von nun an wirst du Menschen fangen – nach einem überwältigenden Fischzug.' },
  },
  'lt-witwe': {
    background: 'Direkt davor warnt Jesus vor Schriftgelehrten, die die Häuser der Witwen fressen und zum Schein lange beten (Markus 12,40). Die arme Witwe ist das Gegenbild: Sie hat wenig und gibt alles.',
    question: 'Jesus misst Gaben nicht an der Summe. Was würde sich ändern, wenn wir Großzügigkeit so messen würden?',
    crossRef: { ref: '2. Korinther 8,12', note: 'Wenn der gute Wille da ist, zählt, was einer hat – nicht, was er nicht hat.' },
  },
  'lt-krippe': {
    background: 'Das Wort für die Unterkunft (katalyma) meint wohl einen Gästeraum; dasselbe Wort steht in Lukas 22,11 für den Raum des letzten Abendmahls. Viele Häuser hatten die Tiere im unteren Teil.',
    question: 'Gott kommt nicht im Palast zur Welt, sondern am Rand. Wo würdet ihr ihn heute am wenigsten erwarten?',
    crossRef: { ref: 'Philipper 2,7', note: 'Christus entäußerte sich selbst und nahm die Gestalt eines Knechts an – die Krippe ist der Anfang dieses Weges.' },
  },
  'lt-lebensbrot': {
    background: 'Die Leute erinnern Jesus an das Manna in der Wüste (Johannes 6,31). Er antwortet: Nicht Mose gab das wahre Brot vom Himmel, sondern der Vater – und dieses Brot ist er selbst.',
    question: 'Wonach „hungert“ ihr – und wo sucht ihr Sättigung, die nicht lange hält?',
    crossRef: { ref: 'Jesaja 55,2', note: 'Warum zahlt ihr Geld für das, was kein Brot ist? Gott lädt zu dem ein, was wirklich satt macht.' },
  },
  'lt-nadeloehr': {
    background: 'Das Nadelöhr ist wörtlich gemeint – eine bewusst übertriebene Bildsprache. Die oft erzählte Deutung als enges Stadttor in Jerusalem kam erst viel später auf und ist nicht belegt.',
    question: 'Wo hindert Besitz – oder die Sorge darum – euch daran, Gott ganz zu vertrauen?',
    crossRef: { ref: '1. Timotheus 6,17', note: 'Paulus rät den Reichen, nicht auf unsicheren Reichtum zu hoffen, sondern auf Gott, der alles reichlich gibt.' },
  },
  'lt-aussaetzige': {
    background: 'Aussätzige mussten Abstand halten und durften nicht in die Orte. Jesus schickt die zehn zu den Priestern, die eine Heilung bestätigen mussten (3. Mose 14) – geheilt wurden sie unterwegs.',
    question: 'Neun gehen weiter, einer kehrt um und dankt. Wofür habt ihr in letzter Zeit vergessen, Danke zu sagen?',
    crossRef: { ref: 'Psalm 103,2', note: 'Der Beter ermahnt sich selbst, Gott zu loben und keine seiner Wohltaten zu vergessen.' },
  },
  'lt-johannes-316': {
    background: 'Im Satz davor erinnert Jesus an die eherne Schlange in der Wüste: Wer sie ansah, blieb am Leben (4. Mose 21,8–9). So muss auch der Menschensohn erhöht werden (Johannes 3,14–15).',
    question: '„So sehr“ – wie verändert es euren Blick auf euch selbst, wenn ihr diesen Vers persönlich nehmt?',
    crossRef: { ref: 'Römer 5,8', note: 'Gott zeigt seine Liebe darin, dass Christus für uns starb, als wir noch Sünder waren.' },
  },
  'lt-peitsche': {
    background: 'Johannes erzählt die Tempelreinigung gleich am Anfang von Jesu Wirken, die anderen Evangelien kurz vor seinem Leiden. Im Vorhof verkaufte man Opfertiere und tauschte Geld in Tempelmünzen.',
    question: 'Jesus wird zornig, wo Gottes Haus zum Geschäft wird. Wo wäre heiliger Zorn heute angebracht?',
    crossRef: { ref: 'Jesaja 56,7', note: 'Gottes Haus soll ein Bethaus für alle Völker heißen – Jesus zitiert das bei der Tempelreinigung (Markus 11,17).' },
  },
  'lt-kana': {
    background: 'Eine Hochzeit dauerte oft eine Woche, und ohne Wein drohte der Familie eine Blamage. Jesus antwortet seiner Mutter zunächst: Meine Stunde ist noch nicht gekommen (Johannes 2,4).',
    question: '„Was er euch sagt, das tut“ – wo fällt es euch schwer, Jesus zu vertrauen, bevor ihr seht, was er vorhat?',
    crossRef: { ref: 'Lukas 1,38', note: 'Schon bei der Ankündigung antwortet Maria: Mir geschehe, wie du gesagt hast – Vertrauen vor dem Verstehen.' },
  },
  'lt-pfingsten': {
    background: 'Pfingsten war ursprünglich das Erntefest Schawuot, 50 Tage nach dem Passa. Darum waren Juden aus der ganzen damaligen Welt in Jerusalem – die Liste in 2,9–11 reicht von Persien bis Rom.',
    question: 'In Babel verwirrten sich die Sprachen, an Pfingsten verstehen sich Menschen. Wo erlebt ihr, dass Gottes Geist Grenzen überwindet?',
    crossRef: { ref: 'Joel 3,1', note: 'Gott will seinen Geist über alle Menschen ausgießen – mit diesem Prophetenwort erklärt Petrus das Pfingstwunder.' },
  },
  'lt-stephanus': {
    background: 'Stephanus war einer der sieben Männer, die für die Versorgung der Witwen gewählt wurden (Apostelgeschichte 6,1–6). Bei seiner Steinigung bewachte ein junger Mann namens Saulus die Kleider.',
    question: 'Stephanus bittet sterbend für die, die ihn steinigen. Wie kann man vergeben, wenn einem Unrecht geschieht?',
    crossRef: { ref: 'Lukas 23,34', note: 'Vater, vergib ihnen – Stephanus betet fast wie Jesus am Kreuz.' },
  },
  'lt-kaemmerer': {
    background: 'Er verwaltete den Schatz der Kandake, der Königin von Äthiopien. Als Eunuch durfte er nach 5. Mose 23,2 nicht zur Gemeinde gehören – Jesaja 56,3–5 verheißt solchen Menschen einen Platz.',
    question: '„Wie kann ich verstehen, wenn mich niemand anleitet?“ Wer hat euch geholfen, die Bibel zu verstehen?',
    crossRef: { ref: 'Jesaja 53,7', note: 'Der Gottesknecht schweigt wie ein Lamm vor seinem Scherer – genau diese Stelle las der Äthiopier.' },
  },
  'lt-malta': {
    background: 'Zwei Wochen lang war das Schiff mit 276 Menschen an Bord durch den Sturm getrieben. Am Ende kamen alle lebend auf Malta an, wie Paulus es angekündigt hatte (Apostelgeschichte 27,22.37.44).',
    question: 'Erst ein Mörder, dann ein Gott – wie schnell urteilen wir über Menschen nach dem, was ihnen gerade passiert?',
    crossRef: { ref: 'Markus 16,18', note: 'Am Ende des Markusevangeliums heißt es, Schlangen würden den Glaubenden nicht schaden – dieser Schluss fehlt in den ältesten Handschriften.' },
  },
  'lt-damaskus': {
    background: 'Saulus war mit Briefen des Hohenpriesters unterwegs, um Anhänger „des Weges“ gefesselt nach Jerusalem zu bringen. So nannte man die ersten Christen (Apostelgeschichte 9,2).',
    question: 'Hananias soll ausgerechnet den gefährlichsten Verfolger besuchen. Wem fällt es euch schwer, eine zweite Chance zu geben?',
    crossRef: { ref: 'Galater 1,13-16', note: 'Paulus erinnert selbst daran, wie er die Gemeinde verfolgte – bis Gott ihm seinen Sohn offenbarte.' },
  },
  'lt-gamaliel': {
    background: 'Der Hohe Rat wollte die Apostel töten, weil sie trotz Verbot weiter von Jesus predigten. Gamaliel war ein hoch angesehener Gesetzeslehrer – sein nüchterner Rat rettete ihnen das Leben.',
    question: '„Ist es von Gott, könnt ihr es nicht aufhalten.“ Wie gelassen geht ihr mit Neuem um, das ihr nicht sofort einordnen könnt?',
    crossRef: { ref: 'Apostelgeschichte 4,19-20', note: 'Schon vorher sagen Petrus und Johannes: Wir können nicht schweigen über das, was wir gesehen und gehört haben.' },
  },
  'lt-zum-besten': {
    background: 'Der Vers steht in einem Kapitel über Seufzen und Leiden: Die Schöpfung seufzt, wir seufzen, und der Geist selbst tritt mit Seufzen für uns ein (Römer 8,22–26).',
    question: 'Wann habt ihr im Rückblick gesehen, dass Gott aus etwas Schwerem Gutes gemacht hat?',
    crossRef: { ref: '1. Mose 50,20', note: 'Josef zu seinen Brüdern: Ihr wolltet mir Böses tun, Gott aber hat es zum Guten gewendet.' },
  },
  'lt-die-groesste': {
    background: 'Paulus beschreibt die Liebe in 13,4–7 im Griechischen fast nur mit Verben: Sie wartet, sie freut sich, sie erträgt. Liebe ist bei ihm vor allem etwas, das man tut.',
    question: 'Paulus beschreibt Liebe mit Taten, nicht mit Gefühlen. Welche dieser Taten fällt euch gerade am schwersten?',
    crossRef: { ref: '1. Johannes 4,16', note: 'Gott ist Liebe, und wer in der Liebe bleibt, bleibt in Gott – die Quelle der Liebe, die nie aufhört.' },
  },
  'lt-aus-gnade': {
    background: 'Die Leser in Ephesus waren größtenteils Nichtjuden. Paulus erinnert sie: Früher wart ihr fern, ohne Hoffnung und ohne Gott – jetzt seid ihr Mitbürger der Heiligen (Epheser 2,12.19).',
    question: 'Warum fällt es so schwer, sich etwas schenken zu lassen, statt es sich zu verdienen?',
    crossRef: { ref: 'Titus 3,5', note: 'Nicht wegen unserer gerechten Werke, sondern aus Barmherzigkeit hat Gott uns gerettet.' },
  },
  'lt-freut-euch': {
    background: 'Im selben Abschnitt: Sorgt euch um nichts, sondern bringt eure Anliegen mit Dank vor Gott. Dann bewahrt der Friede Gottes eure Herzen und Gedanken (Philipper 4,6–7).',
    question: 'Paulus freut sich im Gefängnis. Woher kommt Freude, die nicht von den Umständen abhängt?',
    crossRef: { ref: 'Nehemia 8,10', note: 'Die Freude am HERRN ist eure Stärke – Nehemia tröstet das Volk, das beim Hören des Gesetzes weint.' },
  },
  'lt-pruefet': {
    background: 'Paulus musste Thessalonich schon nach wenigen Wochen verlassen. Trotzdem traut er der jungen Gemeinde zu, selbst zu prüfen – statt alles abzulehnen oder alles zu glauben.',
    question: 'Wie prüft ihr, ob eine Predigt, ein Buch oder ein Video wirklich gut ist?',
    crossRef: { ref: '1. Johannes 4,1', note: 'Glaubt nicht jedem Geist, sondern prüft die Geister, ob sie von Gott sind.' },
  },
  'lt-schrift': {
    background: 'Timotheus kannte die Schriften von Mutter und Großmutter her. Paulus schreibt aus der Haft, vermutlich kurz vor seinem Tod – der Brief ist fast ein Vermächtnis an seinen Schüler (2. Timotheus 4,6).',
    question: 'Wofür ist die Bibel in eurem Leben gerade „nützlich“ – zum Lehren, Zurechtweisen, Bessern oder Erziehen?',
    crossRef: { ref: '2. Petrus 1,21', note: 'Getrieben vom Heiligen Geist haben Menschen im Auftrag Gottes geredet – so beschreibt Petrus die Prophetie.' },
  },
  'lt-mitweinen': {
    background: 'Römer 12 beginnt damit, das ganze Leben Gott hinzugeben. Danach folgen lauter kurze Anweisungen für das Zusammenleben – fast wie eine Liste zum Abhaken.',
    question: 'Bei wem fällt es euch schwerer: euch mitzufreuen oder mitzuweinen – und warum?',
    crossRef: { ref: '1. Korinther 12,26', note: 'Wenn ein Glied leidet, leiden alle mit; wird eins geehrt, freuen sich alle mit – die Gemeinde als ein Leib.' },
  },
  'lt-nicht-sieht': {
    background: 'Die Empfänger waren müde geworden und dachten wohl ans Aufgeben. Der Hebräerbrief stellt ihnen eine ganze „Wolke von Zeugen“ vor Augen, die durchgehalten haben (Hebräer 12,1).',
    question: 'Woran haltet ihr fest, obwohl ihr es (noch) nicht seht?',
    crossRef: { ref: '2. Korinther 5,7', note: 'Wir leben im Glauben und nicht im Schauen – Paulus über das Leben zwischen Hoffnung und Erfüllung.' },
  },
  'lt-langsam': {
    background: 'Jakobus schreibt sehr praktisch: Glaube zeigt sich im Alltag. Immer wieder kommt er dabei auf Worte und die Zunge zurück (Jakobus 1,26; 3,1–12; 4,11).',
    question: 'Was würde sich in euren Gesprächen ändern, wenn ihr diese Reihenfolge – erst hören, dann reden – ernst nehmt?',
    crossRef: { ref: 'Sprüche 15,1', note: 'Eine sanfte Antwort stillt den Zorn, ein kränkendes Wort reizt ihn – Jakobus steht in der Tradition der Weisheit.' },
  },
  'lt-sorgen': {
    background: 'Petrus schreibt an Christen in Kleinasien, die wegen ihres Glaubens schief angesehen und benachteiligt wurden. „Werfen“ meint ein entschlossenes Abladen, wie man eine Last vom Rücken wirft.',
    question: 'Welche Sorge tragt ihr gerade mit euch herum, die ihr heute bewusst „abwerfen“ könntet?',
    crossRef: { ref: 'Psalm 55,23', note: 'Wirf dein Anliegen auf den HERRN, er wird dich versorgen – Petrus greift diesen Psalm auf.' },
  },
  'lt-furcht': {
    background: 'Kurz davor steht der Satz, den viele auswendig kennen: Gott ist Liebe (1. Johannes 4,8.16). Die Liebe beginnt nicht bei uns, sondern bei Gott, der uns zuerst geliebt hat (4,19).',
    question: 'Wo bestimmt Angst euer Verhältnis zu Gott – und was würde sich ändern, wenn Liebe sie verdrängt?',
    crossRef: { ref: 'Römer 8,15', note: 'Ihr habt keinen Geist bekommen, der euch wieder in Angst versetzt, sondern ihr ruft: Abba, Vater!' },
  },
  'lt-derselbe': {
    background: 'Die Empfänger hatten ihre ersten Gemeindeleiter verloren (Hebräer 13,7). Gegen das Gefühl, dass alles unsicher wird, setzt der Brief: Christus ändert sich nicht.',
    question: 'Was verändert sich in eurem Leben gerade – und wie hilft es, dass Christus derselbe bleibt?',
    crossRef: { ref: 'Maleachi 3,6', note: 'Ich, der HERR, ändere mich nicht – Gottes Treue ist der Grund, warum es sein Volk noch gibt.' },
  },
  'lt-a-und-o': {
    background: 'Die Offenbarung richtet sich an Gemeinden unter Druck. Gleich zu Beginn stellt sie klar: Wer am Anfang steht, steht auch am Ende – die Geschichte läuft nicht aus dem Ruder.',
    question: 'Was bedeutet es für euren Alltag, dass Gott Anfang und Ende in der Hand hält?',
    crossRef: { ref: 'Jesaja 44,6', note: 'Ich bin der Erste und der Letzte, und außer mir ist kein Gott – das Vorbild für „A und O“.' },
  },
  'lt-anklopfen': {
    background: 'Laodizea war eine reiche Stadt mit Banken, Textilhandel und einer bekannten Augensalbe. Gerade dieser Gemeinde sagt Christus: Du bist arm, blind und nackt (Offenbarung 3,17–18).',
    question: 'Wo steht Jesus in eurem Leben „vor der Tür“ – und was hält euch davon ab, sie zu öffnen?',
    crossRef: { ref: 'Lukas 12,36', note: 'Seid wie Knechte, die auf ihren Herrn warten, um ihm sofort zu öffnen, wenn er kommt und anklopft.' },
  },
  'lt-traenen': {
    background: 'Unmittelbar davor heißt es: Gottes Wohnung ist bei den Menschen. Das Ziel der Bibel ist nicht der Weg weg von der Welt, sondern Gott mitten in einer neuen Welt (Offenbarung 21,3).',
    question: 'Welche Tränen – eigene oder fremde – möchtet ihr Gott heute hinlegen und auf seine Zusage hoffen?',
    crossRef: { ref: 'Psalm 56,9', note: 'Der Beter bittet Gott, seine Tränen in einen Krug zu sammeln – keine Träne geht bei Gott verloren.' },
  },
  'lt-perlentor': {
    background: 'Die zwölf Tore tragen die Namen der zwölf Stämme Israels, die zwölf Grundsteine die Namen der zwölf Apostel (21,12–14) – Gottes Volk aus Altem und Neuem Testament gehört zusammen.',
    question: 'Perlen entstehen, wenn eine Muschel verletzt wird. Was könnte dieses Bild für die Tore zur neuen Welt bedeuten?',
    crossRef: { ref: 'Matthäus 13,45-46', note: 'Ein Kaufmann verkauft alles für eine einzige kostbare Perle – Gottes Reich ist jeden Preis wert.' },
  },
  'lt-leuchter': {
    background: 'Die sieben Gemeinden lagen in der heutigen Westtürkei auf einer Art Rundweg von Ephesus bis Laodizea. Ein Bote konnte die Briefe der Reihe nach überbringen.',
    question: 'Eine Gemeinde als Leuchter: Was müsste geschehen, damit eure Gemeinde für ihren Ort mehr leuchtet?',
    crossRef: { ref: 'Matthäus 5,14-16', note: 'Ihr seid das Licht der Welt; niemand stellt ein Licht unter einen Eimer, sondern auf einen Leuchter.' },
  },
};
