// Kuratierter Fragenpool – abgeleitet aus dem „Studienkonzept NT“ (Lernblätter zu allen 27 Büchern),
// ergänzt um geprüfte Fragen aus dem „Bible Bluff“-Fragenpool vom 8. Oktober 2026 (auch zum Alten Testament).
// Liegt nur auf dem Server: Der Browser bekommt nie Antworten oder Bluff-Vorschläge auf Vorrat.
//
// Aufbau einer Frage:
//  prompt     – die Frage, wie sie auf den Handys erscheint
//  answer     – die richtige Antwort, im Stil eines Bluffs formuliert (kurz, ohne Klammern)
//  accept     – Schlüsselwort-Gruppen, an denen ein Bluff als „zu nah an der Wahrheit“ erkannt wird
//               ("wort" = Wortanfang, "*wort" = enthält, "=wort" = genau dieses Wort)
//  bluffs     – vorbereitete falsche Antworten (Vorschläge und Hausbluffs)
//  ref        – Bibelstelle für die Auflösung
//  discovery  – ein kurzer, überraschender Satz zur Entdeckung
//  number     – Zahlenfrage (pro Partie höchstens zwei)

import type { BookGroup } from '../shared/types';

export interface Question {
  id: string;
  book: string;
  group: BookGroup;
  difficulty: 1 | 2 | 3;
  prompt: string;
  answer: string;
  variants?: string[];
  accept: string[][];
  bluffs: string[];
  ref: string;
  discovery: string;
  number?: boolean;
}

export const QUESTIONS: Question[] = [
  // ───────────── Matthäus ─────────────
  {
    id: 'mt-schlangen',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Jesus sendet seine Jünger aus. Klug wie … und ohne Falsch wie …?',
    answer: 'Schlangen und Tauben',
    accept: [['schlang', 'taub']],
    bluffs: ['Füchse und Lämmer', 'Eulen und Schafe', 'Raben und Spatzen'],
    ref: 'Matthäus 10,16',
    discovery: 'Jesus will keine naiven Boten: Sie sollen klug handeln und dabei lauter bleiben.',
  },
  {
    id: 'mt-muenze',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Wo fand Petrus das Geld für die Tempelsteuer?',
    answer: 'Im Maul eines Fisches',
    accept: [['*fisch']],
    bluffs: ['Unter einem Stein am Seeufer', 'Im Saum seines Mantels', 'In einem Krug am Brunnen'],
    ref: 'Matthäus 17,24-27',
    discovery: 'Jesus zahlt die Steuer, um keinen Anstoß zu geben – und versorgt Petrus gleich mit.',
  },
  {
    id: 'mt-traum',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Warum ließ die Frau des Pilatus ihrem Mann ausrichten, er solle Jesus nichts antun?',
    answer: 'Sie hatte seinetwegen einen schlimmen Traum',
    accept: [['traum'], ['traeum'], ['*getraeum']],
    bluffs: ['Wegen eines Erdbebens in der Nacht', 'Weil ihre Dienerin Jesus kannte', 'Weil ein Stern über dem Palast stand'],
    ref: 'Matthäus 27,19',
    discovery: 'Nur Matthäus erzählt davon: Mitten im Prozess nennt eine Stimme aus dem Palast Jesus einen Gerechten.',
  },
  {
    id: 'mt-immanuel',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Was bedeutet der Name Immanuel, den Matthäus auf Jesus bezieht?',
    answer: 'Gott mit uns',
    accept: [['gott', '=mit'], ['=mit', '=uns']],
    bluffs: ['Gott rettet', 'Licht der Völker', 'Gesandter des Höchsten'],
    ref: 'Matthäus 1,23',
    discovery: 'Matthäus beginnt mit „Gott mit uns“ und endet mit Jesu Zusage: Ich bin bei euch alle Tage (28,20).',
  },
  {
    id: 'mt-reden',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 3,
    prompt: 'Wie viele große Redeblöcke Jesu enthält das Matthäusevangelium?',
    answer: 'Fünf',
    accept: [['=fuenf'], ['=5']],
    bluffs: ['Sieben', 'Drei', 'Zwölf'],
    ref: 'Matthäus 5-7; 10; 13; 18; 24-25',
    discovery: 'Bergpredigt, Aussendung, Gleichnisse, Gemeinde, Wiederkunft. Viele erinnert das an die fünf Bücher Mose.',
    number: true,
  },
  {
    id: 'mt-zuerst',
    book: 'Matthäus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Was sollen Jesu Nachfolger laut Bergpredigt zuerst suchen?',
    answer: 'Gottes Reich und seine Gerechtigkeit',
    accept: [['reich'], ['*koenigreich'], ['gerecht']],
    bluffs: ['Frieden mit den Nachbarn', 'Den Segen der Eltern', 'Die Stille vor Sonnenaufgang'],
    ref: 'Matthäus 6,33',
    discovery: 'Der Satz steht mitten in Jesu Worten gegen das Sorgen: Wer Gott den Vorrang gibt, muss das Morgen nicht fürchten.',
  },

  // ───────────── Markus ─────────────
  {
    id: 'mk-leinentuch',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Was ließ ein junger Mann zurück, als er bei Jesu Gefangennahme floh?',
    answer: 'Sein Leinentuch, er floh nackt',
    accept: [['*leinen'], ['*tuch'], ['nackt'], ['*gewand'], ['*kleid'], ['*mantel'], ['*hemd'], ['*umhang']],
    bluffs: ['Eine brennende Fackel', 'Seinen Geldbeutel', 'Einen Krug mit Wasser'],
    ref: 'Markus 14,51-52',
    discovery: 'Nur Markus erzählt das. Manche vermuten, der junge Mann sei Markus selbst gewesen – sicher ist das nicht.',
  },
  {
    id: 'mk-effata',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Was bedeutet das aramäische Wort „Effata“, das Jesus bei einer Heilung spricht?',
    answer: 'Tu dich auf',
    variants: ['Öffne dich'],
    accept: [['=tu', '=auf'], ['oeffne'], ['geoeffnet'], ['offen']],
    bluffs: ['Sei geheilt', 'Friede sei mit dir', 'Steh auf und geh'],
    ref: 'Markus 7,31-37',
    discovery: 'Markus bewahrt Jesu Muttersprache: Im Alltag sprach Jesus Aramäisch.',
  },
  {
    id: 'mk-dach',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Wie brachten vier Männer einen Gelähmten zu Jesus, als das Haus überfüllt war?',
    answer: 'Sie deckten das Dach ab und ließen ihn hinunter',
    accept: [['dach'], ['ziegel']],
    bluffs: ['Sie reichten ihn durchs Fenster', 'Sie trugen ihn durch den Hof der Nachbarn', 'Sie riefen, bis alle Platz machten'],
    ref: 'Markus 2,1-12',
    discovery: 'Jesus sieht ihren Glauben und vergibt dem Mann zuerst seine Sünden, bevor er ihn heilt.',
  },
  {
    id: 'mk-kissen',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Worauf schlief Jesus im Boot, während der Sturm tobte?',
    answer: 'Auf einem Kissen im Heck',
    accept: [['kissen'], ['heck'], ['polster']],
    bluffs: ['Auf einem Netz am Bug', 'Auf einem Sack Getreide', 'Auf der Ruderbank'],
    ref: 'Markus 4,35-41',
    discovery: 'Nur Markus erwähnt das Kissen. Ein kleines Detail, das zeigt: Jesus war wirklich Mensch – und todmüde.',
  },
  {
    id: 'mk-hauptmann',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Wer sagt bei Markus unter dem Kreuz: Dieser Mensch war wirklich Gottes Sohn?',
    answer: 'Ein römischer Hauptmann',
    accept: [['hauptmann'], ['*zenturio'], ['*centurio'], ['offizier']],
    bluffs: ['Einer der beiden Verbrecher', 'Josef von Arimathäa', 'Ein Pharisäer aus dem Hohen Rat'],
    ref: 'Markus 15,39',
    discovery: 'Ausgerechnet ein Offizier Roms spricht aus, worauf das ganze Evangelium zielt (Markus 1,1).',
  },

  {
    id: 'mk-heuschrecken',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Welche ungewöhnliche Kombination aß Johannes der Täufer?',
    answer: 'Heuschrecken und wilden Honig',
    accept: [['heuschreck'], ['*honig'], ['grashuepf']],
    bluffs: ['Datteln und Ziegenkäse', 'Getrocknete Feigen und Fladenbrot', 'Wurzeln und Quellwasser'],
    ref: 'Markus 1,6',
    discovery: 'Mantel aus Kamelhaar, Ledergürtel, Heuschrecken: Johannes lebte wie der Prophet Elia (2. Könige 1,8). Wer ihn sah, sollte an den Wegbereiter denken, den Maleachi angekündigt hatte.',
  },
  {
    id: 'mk-donnersoehne',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Welchen gemeinsamen Beinamen gab Jesus den Brüdern Jakobus und Johannes?',
    answer: 'Donnersöhne',
    variants: ['Söhne des Donners', 'Boanerges'],
    accept: [['donner'], ['boanerges']],
    bluffs: ['Felsenbrüder', 'Söhne der Morgenröte', 'Eiferer des Herrn'],
    ref: 'Markus 3,17; Lukas 9,54',
    discovery: 'Der Name passte: Die beiden wollten einmal Feuer vom Himmel auf ein Dorf fallen lassen, das Jesus nicht aufnahm. Jesus wies sie zurecht und machte aus den Hitzköpfen Apostel. Jakobus starb später als Erster der Zwölf für seinen Glauben (Apostelgeschichte 12,2).',
  },
  {
    id: 'mk-wasserkrug',
    book: 'Markus',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Was trug der Mann, dem zwei Jünger folgen sollten, um den Raum für das Passamahl zu finden?',
    answer: 'Einen Wasserkrug',
    variants: ['Einen Krug mit Wasser'],
    accept: [['*krug'], ['*wasser'], ['*gefaess'], ['amphore']],
    bluffs: ['Ein Lamm auf den Schultern', 'Einen roten Mantel', 'Eine brennende Öllampe'],
    ref: 'Markus 14,12–16',
    discovery: 'Wasser trugen damals meist Frauen, ein Mann mit Krug fiel also auf. Die Jünger fanden alles so vor, wie Jesus es gesagt hatte, bis hin zum vorbereiteten Saal im Obergeschoss.',
  },

  // ───────────── Lukas ─────────────
  {
    id: 'lk-zachaeus',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Auf was für einen Baum kletterte Zachäus, um Jesus zu sehen?',
    answer: 'Auf einen Maulbeerfeigenbaum',
    variants: ['Sykomore'],
    accept: [['*maulbeer'], ['sykomor'], ['*feige']],
    bluffs: ['Auf eine Dattelpalme', 'Auf einen Olivenbaum', 'Auf eine Zeder am Stadttor'],
    ref: 'Lukas 19,1-10',
    discovery: 'Zachäus war klein und als Oberzöllner verachtet. Jesus lädt sich trotzdem bei ihm ein.',
  },
  {
    id: 'lk-adam',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Bis zu wem führt Lukas den Stammbaum Jesu zurück?',
    answer: 'Bis zu Adam',
    accept: [['adam']],
    bluffs: ['Bis zu Abraham', 'Bis zu Noah', 'Bis zu König David'],
    ref: 'Lukas 3,23-38',
    discovery: 'Matthäus beginnt bei Abraham, Lukas geht bis Adam zurück: Jesu Sendung gilt der ganzen Menschheit.',
  },
  {
    id: 'lk-zwoelf',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Wie alt war Jesus, als ihn seine Eltern nach drei Tagen Suche im Tempel fanden?',
    answer: 'Zwölf Jahre',
    accept: [['=zwoelf'], ['=12']],
    bluffs: ['Zehn Jahre', 'Dreizehn Jahre', 'Sieben Jahre'],
    ref: 'Lukas 2,41-52',
    discovery: 'Es ist die einzige Szene aus Jesu Kindheit nach den Geburtsberichten – und nur Lukas erzählt sie.',
    number: true,
  },
  {
    id: 'lk-johanna',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 3,
    prompt: 'Wessen Ehefrau unterstützte Jesus und seine Jünger mit ihrem Vermögen?',
    answer: 'Die Frau eines Verwalters von Herodes',
    accept: [['herodes'], ['chusa'], ['chuza'], ['johanna']],
    bluffs: ['Die Frau eines Hohepriesters', 'Die Frau des Pilatus', 'Die Witwe eines Zöllners'],
    ref: 'Lukas 8,1-3',
    discovery: 'Frauen gehörten zum Kreis um Jesus und trugen seinen Dienst mit – sogar aus dem Umfeld des Herodes.',
  },
  {
    id: 'lk-emmaus',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Woran erkannten die beiden Jünger in Emmaus den Auferstandenen?',
    answer: 'Als er das Brot brach',
    accept: [['*brot'], ['brach'], ['*brech']],
    bluffs: ['Als er ihre Namen rief', 'Als er einen Psalm anstimmte', 'An seinem Reisemantel'],
    ref: 'Lukas 24,13-35',
    discovery: 'Unterwegs hatte er ihnen die Schriften erklärt. Erkannt haben sie ihn erst am Tisch.',
  },
  {
    id: 'lk-samariter',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Was gab der barmherzige Samariter dem Wirt für die Pflege des Verletzten?',
    answer: 'Zwei Silbergroschen',
    variants: ['Zwei Denare'],
    accept: [['denar'], ['*silber'], ['*groschen']],
    bluffs: ['Seinen Esel als Pfand', 'Einen goldenen Ring', 'Einen Sack Gerste'],
    ref: 'Lukas 10,25-37',
    discovery: 'Zwei Denare waren etwa zwei Tageslöhne – und er versprach, alles Weitere bei seiner Rückkehr zu bezahlen.',
  },
  {
    id: 'lk-verloren',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Welche drei verlorenen Dinge stehen in Lukas 15 im Mittelpunkt?',
    answer: 'Ein Schaf, eine Münze und ein Sohn',
    accept: [['schaf', 'muenz'], ['schaf', 'sohn'], ['muenz', 'sohn'], ['*drachme'], ['*groschen', 'sohn'], ['*groschen', 'schaf']],
    bluffs: ['Ein Esel, ein Schlüssel und eine Tochter', 'Ein Lamm, ein Krug und ein Knecht', 'Eine Ziege, ein Ring und ein Bruder'],
    ref: 'Lukas 15',
    discovery: 'Alle drei Gleichnisse enden mit einem Fest: Gott freut sich über jeden Menschen, der umkehrt.',
  },

  {
    id: 'lk-fisch',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Was aß der auferstandene Jesus laut Lukas vor den Augen seiner Jünger?',
    answer: 'Ein Stück gebratenen Fisch',
    variants: ['Fisch', 'Gebratenen Fisch'],
    accept: [['*fisch'], ['*honig']],
    bluffs: ['Ein Stück Fladenbrot', 'Eine Handvoll Datteln', 'Geröstete Ähren'],
    ref: 'Lukas 24,36–43',
    discovery: 'Die Jünger hielten ihn für ein Gespenst. Jesus lässt sich anfassen und isst vor ihren Augen: Der Auferstandene ist kein Geist, sondern leibhaftig da.',
  },
  {
    id: 'lk-fuchs',
    book: 'Lukas',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Mit welchem Tiernamen bezeichnete Jesus König Herodes?',
    answer: 'Fuchs',
    variants: ['Dieser Fuchs'],
    accept: [['fuchs'], ['*fuechs']],
    bluffs: ['Schakal', 'Natter', 'Aasgeier'],
    ref: 'Lukas 13,31–33',
    discovery: 'Pharisäer warnen Jesus, Herodes wolle ihn töten. Jesus lässt dem „Fuchs“ ausrichten, dass er seinen Weg trotzdem weitergeht: Sterben wird er nicht in Galiläa, sondern in Jerusalem.',
  },

  // ───────────── Johannes ─────────────
  {
    id: 'joh-kana',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Wie viele steinerne Wasserkrüge standen bei der Hochzeit in Kana bereit?',
    answer: 'Sechs',
    accept: [['=sechs'], ['=6']],
    bluffs: ['Zwölf', 'Sieben', 'Drei'],
    ref: 'Johannes 2,1-11',
    discovery: 'Jeder Krug fasste rund 100 Liter. Jesu erstes Zeichen schenkt Wein in verschwenderischer Fülle.',
    number: true,
  },
  {
    id: 'joh-153',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Wie viele große Fische zählten die Jünger nach dem Fang am See Tiberias?',
    answer: '153',
    accept: [['=153'], ['hundertdreiundfuenfzig']],
    bluffs: ['144', '120', '77'],
    ref: 'Johannes 21,1-14',
    discovery: 'Trotz der Menge zerriss das Netz nicht. Kurz darauf beauftragt Jesus Petrus neu.',
    number: true,
  },
  {
    id: 'joh-junge',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Was hatte der Junge bei der Speisung der Fünftausend laut Johannes dabei?',
    answer: 'Fünf Gerstenbrote und zwei Fische',
    accept: [['*gerste'], ['=fuenf', '*brot'], ['*fisch']],
    bluffs: ['Drei Fladenbrote und einen Krug Milch', 'Sieben Feigen und etwas Käse', 'Einen Korb voller Datteln'],
    ref: 'Johannes 6,1-13',
    discovery: 'Nur Johannes erwähnt den Jungen – und dass es Gerstenbrot war, das Brot der einfachen Leute.',
  },
  {
    id: 'joh-handschriften',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 3,
    prompt: 'Welche Erzählung aus dem Johannesevangelium fehlt in wichtigen frühen Handschriften?',
    answer: 'Jesus und die Ehebrecherin',
    accept: [['ehebrech'], ['ehebruch']],
    bluffs: ['Die Hochzeit zu Kana', 'Das Gespräch mit Nikodemus', 'Die Fußwaschung'],
    ref: 'Johannes 7,53-8,11',
    discovery: 'Viele Bibelausgaben setzen den Abschnitt deshalb in Klammern oder markieren ihn eigens.',
  },
  {
    id: 'joh-ichbin',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Wie viele bildhafte „Ich bin“-Worte Jesu zählt man im Johannesevangelium?',
    answer: 'Sieben',
    accept: [['=sieben'], ['=7']],
    bluffs: ['Zwölf', 'Fünf', 'Zehn'],
    ref: 'Johannes 6; 8; 10; 11; 14; 15',
    discovery: 'Brot, Licht, Tür, Hirte, Auferstehung, Weg und Weinstock: Jedes Bild zeigt, wer Jesus ist.',
    number: true,
  },
  {
    id: 'joh-nikodemus',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Wann kam Nikodemus zum ersten Mal zu Jesus?',
    answer: 'In der Nacht',
    accept: [['nacht'], ['*dunkel']],
    bluffs: ['Im Morgengrauen', 'Zur Mittagszeit', 'Am Sabbat nach dem Gottesdienst'],
    ref: 'Johannes 3,1-2',
    discovery: 'Später verteidigt Nikodemus Jesus und hilft sogar bei seinem Begräbnis (7,50-51; 19,39).',
  },
  {
    id: 'joh-brunnen',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Um welche Tageszeit traf Jesus die Frau aus Samarien am Brunnen?',
    answer: 'Gegen Mittag',
    variants: ['Um die sechste Stunde'],
    accept: [['mittag'], ['sechst'], ['=12'], ['=zwoelf']],
    bluffs: ['Bei Sonnenaufgang', 'Kurz vor Sonnenuntergang', 'Mitten in der Nacht'],
    ref: 'Johannes 4,5-10',
    discovery: 'In der Mittagshitze ist Jesus müde und durstig – und bittet eine Fremde um Wasser.',
  },

  {
    id: 'joh-speichel',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Woraus machte Jesus einen Brei für die Augen eines blind geborenen Mannes?',
    answer: 'Aus Erde und Speichel',
    variants: ['Aus Spucke und Erde'],
    accept: [['speichel'], ['*spuck'], ['=erde'], ['lehm'], ['staub'], ['schlamm'], ['dreck']],
    bluffs: ['Aus Öl und Asche', 'Aus Wein und Myrrhe', 'Aus Honig und Salz'],
    ref: 'Johannes 9,1–7',
    discovery: 'Danach schickt Jesus den Mann zum Teich Siloah, das heißt „gesandt“. Er wäscht sich und kann sehen. Am Ende des Kapitels sieht der Geheilte klarer als die Gelehrten, die ihn verhören.',
  },
  {
    id: 'joh-obergewand',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 3,
    prompt: 'Was zog Petrus an, bevor er ins Wasser sprang, als er Jesus am Ufer erkannte?',
    answer: 'Sein Obergewand',
    variants: ['Sein Gewand'],
    accept: [['*gewand'], ['*kleid'], ['mantel'], ['umhang'], ['ueberwurf']],
    bluffs: ['Seine Sandalen', 'Einen Strick um den Bauch', 'Seine Fischerkappe'],
    ref: 'Johannes 21,7',
    discovery: 'Zum Schwimmen zieht man sich eigentlich aus. Petrus macht es umgekehrt: Er hatte nackt gearbeitet und wollte so nicht vor seinen Herrn treten. Dann springt er ins Wasser, so eilig hat er es zu Jesus.',
  },
  {
    id: 'joh-haare',
    book: 'Johannes',
    group: 'evangelien',
    difficulty: 1,
    prompt: 'Womit trocknete Maria in Betanien Jesu Füße, nachdem sie sie gesalbt hatte?',
    answer: 'Mit ihren Haaren',
    variants: ['Mit ihrem Haar'],
    accept: [['haar'], ['*haare'], ['locken'], ['zoepfe']],
    bluffs: ['Mit ihrem Schleier', 'Mit einem Leinentuch', 'Mit dem Saum ihres Kleides'],
    ref: 'Johannes 12,1–8',
    discovery: 'Ein Pfund kostbares Nardenöl, das ganze Haus duftete danach. Dass eine Frau dafür ihr Haar löste, war ungewöhnlich. Jesus verteidigt ihre verschwenderische Liebe gegen die Kritik des Judas.',
  },

  // ───────────── Apostelgeschichte ─────────────
  {
    id: 'apg-eutychus',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Was passierte Eutychus, als Paulus bis Mitternacht predigte?',
    answer: 'Er schlief ein und fiel aus dem Fenster',
    accept: [['fenster'], ['=fiel'], ['*sturz'], ['*stuerz'], ['gefallen']],
    bluffs: ['Seine Lampe setzte den Vorhang in Brand', 'Er holte heimlich Brot für alle', 'Er stellte so viele Fragen, dass Paulus aufhörte'],
    ref: 'Apostelgeschichte 20,7-12',
    discovery: 'Er stürzte aus dem dritten Stock. Paulus umarmte ihn, er lebte – und dann redeten sie weiter bis zum Morgen.',
  },
  {
    id: 'apg-korb',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Wie floh Paulus aus Damaskus?',
    answer: 'In einem Korb über die Stadtmauer',
    accept: [['korb'], ['*mauer']],
    bluffs: ['Als Händler verkleidet durchs Stadttor', 'Versteckt unter einer Ladung Wolle', 'Durch einen Abwasserkanal'],
    ref: 'Apostelgeschichte 9,23-25',
    discovery: 'Der große Apostel beginnt mit einer Flucht im Korb. Später zählt er das selbst zu seiner Schwachheit (2. Korinther 11,30-33).',
  },
  {
    id: 'apg-saulus',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 3,
    prompt: 'Wann bekam Saulus laut Apostelgeschichte den Namen Paulus?',
    answer: 'Gar nicht, er hatte von Anfang an zwei Namen',
    accept: [['=gar', 'nicht'], ['zwei', 'name'], ['beide', 'name'], ['*doppel'], ['=nie'], ['niemals']],
    bluffs: ['Bei seiner Taufe in Damaskus', 'Als er vor Damaskus erblindete', 'Bei seiner Aussendung in Antiochia'],
    ref: 'Apostelgeschichte 13,9',
    discovery: '„Saulus, der auch Paulus heißt“: ein jüdischer und ein römischer Name. Von einer Umbenennung bei der Bekehrung erzählt die Bibel nicht.',
  },
  {
    id: 'apg-christen',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Wo wurden die Jünger zum ersten Mal „Christen“ genannt?',
    answer: 'In Antiochia',
    accept: [['antioch']],
    bluffs: ['In Jerusalem', 'In Rom', 'In Damaskus'],
    ref: 'Apostelgeschichte 11,19-26',
    discovery: 'Antiochia wurde zum Missionszentrum: Von dort wurden Barnabas und Paulus ausgesandt (13,1-3).',
  },
  {
    id: 'apg-lydia',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Womit handelte Lydia, die erste Gläubige in Philippi?',
    answer: 'Mit Purpurstoffen',
    accept: [['*purpur']],
    bluffs: ['Mit Olivenöl', 'Mit Weihrauch aus Arabien', 'Mit Tonkrügen'],
    ref: 'Apostelgeschichte 16,13-15',
    discovery: 'Die Gemeinde in Philippi beginnt bei einer Geschäftsfrau am Fluss – und trifft sich in ihrem Haus.',
  },
  {
    id: 'apg-schatten',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Was erhofften sich die Menschen, als sie Kranke auf die Straße trugen, wo Petrus vorbeikam?',
    answer: 'Dass wenigstens sein Schatten auf sie fiel',
    accept: [['schatten']],
    bluffs: ['Dass er sie mit Öl salbte', 'Dass sein Gürtel sie streifte', 'Dass er ihre Namen aufschrieb'],
    ref: 'Apostelgeschichte 5,12-16',
    discovery: 'Lukas berichtet erstaunliche Heilungen in der jungen Gemeinde. Sie geschehen im Namen Jesu, nicht aus eigener Kraft (3,12-16).',
  },
  {
    id: 'apg-landkarte',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Welche Stationen nennt Jesus in Apostelgeschichte 1,8 für das Zeugnis seiner Jünger?',
    answer: 'Jerusalem, Judäa, Samarien und die Enden der Erde',
    accept: [['samari'], ['*ende', 'erde'], ['*ende', 'welt']],
    bluffs: ['Galiläa, Syrien, Griechenland und Rom', 'Jerusalem, Damaskus, Antiochia und Rom', 'Bethlehem, Nazareth, Kapernaum und Ägypten'],
    ref: 'Apostelgeschichte 1,8',
    discovery: 'Der Vers ist das Inhaltsverzeichnis des Buches: Die Geschichte folgt genau dieser Landkarte.',
  },
  {
    id: 'apg-rhode',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Was tat die Magd Rhode, als der befreite Petrus an die Tür klopfte?',
    answer: 'Sie ließ ihn vor lauter Freude draußen stehen',
    accept: [['*drauss'], ['*freude'], ['*vergass'], ['*vergess'], ['stehen', 'lassen']],
    bluffs: ['Sie hielt ihn für einen Dieb', 'Sie fiel in Ohnmacht', 'Sie rief die römische Wache'],
    ref: 'Apostelgeschichte 12,12-17',
    discovery: 'Die Gemeinde betete für Petrus – und erklärte Rhode für verrückt, als sie sagte, er stehe vor der Tür.',
  },

  {
    id: 'apg-zeltmacher',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 1,
    prompt: 'Welches Handwerk übte Paulus gemeinsam mit Aquila und Priszilla aus?',
    answer: 'Zeltmacher',
    variants: ['Zelte machen', 'Zeltmacherei'],
    accept: [['*zelt'], ['*leder'], ['sattler']],
    bluffs: ['Töpfer', 'Zimmermann', 'Fischer'],
    ref: 'Apostelgeschichte 18,1–4; 20,34',
    discovery: 'Paulus finanzierte seine Mission oft selbst, um niemandem zur Last zu fallen (1. Thessalonicher 2,9). Unter der Woche Werkstatt, am Sabbat Synagoge.',
  },
  {
    id: 'apg-los',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Wie wurde zwischen den beiden Kandidaten für die Nachfolge des Judas entschieden?',
    answer: 'Durch das Los',
    variants: ['Sie warfen das Los', 'Per Los'],
    accept: [['=los'], ['=lose'], ['losen'], ['losent'], ['losverf'], ['*loste'], ['*ausgelost'], ['wuerfel'], ['*zufall']],
    bluffs: ['Durch eine Abstimmung der Gemeinde', 'Petrus bestimmte ihn allein', 'Der Ältere wurde genommen'],
    ref: 'Apostelgeschichte 1,15–26',
    discovery: 'Erst stellten sie zwei bewährte Männer auf und beteten, dann fiel das Los auf Matthias. Danach erzählt die Apostelgeschichte von keinem Losentscheid mehr: Nach Pfingsten führt der Heilige Geist die Gemeinde.',
  },
  {
    id: 'apg-tuecher',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 3,
    prompt: 'Welche Alltagsgegenstände von Paulus brachte man laut Apostelgeschichte zu den Kranken?',
    answer: 'Seine Schweißtücher und Schürzen',
    variants: ['Tücher', 'Schweißtücher'],
    accept: [['*tuch'], ['*tuech'], ['schuerz'], ['lappen']],
    bluffs: ['Seine Sandalen', 'Seinen Wanderstab', 'Seinen Trinkbecher'],
    ref: 'Apostelgeschichte 19,11–16',
    discovery: 'Lukas betont: Gott wirkte diese ungewöhnlichen Taten durch Paulus. Gleich danach scheitern Beschwörer, die den Namen Jesu wie eine Zauberformel benutzen wollen.',
  },
  {
    id: 'apg-tabita',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Was bedeutet der Name Tabita, den die Apostelgeschichte übersetzt?',
    answer: 'Gazelle',
    variants: ['Reh'],
    accept: [['gazell'], ['=reh'], ['rehlein'], ['hirschkuh'], ['antilope'], ['*hindin']],
    bluffs: ['Lilie', 'Taube', 'Morgenstern'],
    ref: 'Apostelgeschichte 9,36–42',
    discovery: 'Tabita heißt „Jüngerin“, die weibliche Form steht im Neuen Testament nur hier. Sie nähte Kleider für Witwen. Nach ihrem Tod zeigen die Frauen Petrus weinend ihre Arbeit, und er erweckt sie.',
  },
  {
    id: 'apg-unbekannt',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 2,
    prompt: 'Welche ungewöhnliche Widmung fand Paulus auf einem Altar in Athen?',
    answer: 'Dem unbekannten Gott',
    variants: ['Einem unbekannten Gott'],
    accept: [['unbekannt'], ['*unbekannt'], ['*namenlos']],
    bluffs: ['Dem Gott der Philosophen', 'Den Göttern des Meeres', 'Dem Herrn des Himmels'],
    ref: 'Apostelgeschichte 17,22–31',
    discovery: 'Paulus knüpft daran an: „Was ihr unwissend verehrt, das verkündige ich euch.“ Er zitiert sogar griechische Dichter und holt die Athener dort ab, wo sie stehen.',
  },
  {
    id: 'apg-betrunken',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 1,
    prompt: 'Welche Erklärung hatten manche Spötter für das Geschehen an Pfingsten?',
    answer: 'Sie seien betrunken',
    variants: ['Sie sind voll süßen Weins'],
    accept: [['*trunken'], ['*wein'], ['besoffen'], ['*rausch'], ['=voll'], ['=blau'], ['*alkohol'], ['*getrunken']],
    bluffs: ['Sie hätten Fieber', 'Sie wollten Unruhe stiften', 'Sie seien Zauberer aus dem Osten'],
    ref: 'Apostelgeschichte 2,12–16',
    discovery: 'Petrus kontert trocken: Es ist erst die dritte Stunde, also neun Uhr morgens. Dann erklärt er, was wirklich geschieht: Die Verheißung aus dem Propheten Joel erfüllt sich.',
  },
  {
    id: 'apg-loblieder',
    book: 'Apostelgeschichte',
    group: 'geschichte',
    difficulty: 1,
    prompt: 'Was taten Paulus und Silas um Mitternacht im Gefängnis, sodass die Mitgefangenen zuhörten?',
    answer: 'Sie beteten und lobten Gott',
    variants: ['Sie sangen Loblieder'],
    accept: [['bete'], ['*gebet'], ['*lob'], ['*sang'], ['sing'], ['lied'], ['*loblied'], ['psalm'], ['*hymn'], ['*preis']],
    bluffs: ['Sie gruben einen Tunnel', 'Sie erzählten Geschichten aus der Schrift', 'Sie schliefen tief und fest'],
    ref: 'Apostelgeschichte 16,22–34',
    discovery: 'Mit wunden Rücken und den Füßen im Block singen sie mitten in der Nacht. Nach dem Erdbeben flieht keiner, und der Aufseher fragt: „Was muss ich tun, dass ich gerettet werde?“ Noch in derselben Nacht lässt er sich mit seinem Haus taufen.',
  },

  // ───────────── Römer ─────────────
  {
    id: 'roem-tertius',
    book: 'Römer',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Wer schrieb den Römerbrief nach eigener Angabe nieder?',
    answer: 'Tertius',
    accept: [['tertiu']],
    bluffs: ['Silas', 'Lukas, der Arzt', 'Phöbe aus Kenchreä'],
    ref: 'Römer 16,22',
    discovery: 'Paulus diktierte – und Tertius grüßt mitten in den Schlussgrüßen sogar selbst.',
  },
  {
    id: 'roem-spanien',
    book: 'Römer',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wohin wollte Paulus nach seinem Besuch in Rom weiterreisen?',
    answer: 'Nach Spanien',
    accept: [['spanien'], ['hispan'], ['iberi']],
    bluffs: ['Nach Ägypten', 'Nach Gallien', 'Nach Britannien'],
    ref: 'Römer 15,22-29',
    discovery: 'Rom sollte nur Zwischenstation sein. Paulus bittet die Gemeinde, seine Spanienmission zu unterstützen.',
  },
  {
    id: 'roem-phoebe',
    book: 'Römer',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Welche Frau empfiehlt Paulus als Dienerin der Gemeinde in Kenchreä?',
    answer: 'Phöbe',
    accept: [['phoeb'], ['phob'], ['phoib'], ['foeb']],
    bluffs: ['Lydia', 'Damaris', 'Tabita'],
    ref: 'Römer 16,1-2',
    discovery: 'Römer 16 würdigt viele Mitarbeitende – darunter auffällig viele Frauen.',
  },
  {
    id: 'roem-kohlen',
    book: 'Römer',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was sammelt man laut Römer 12 auf dem Kopf seines Feindes, wenn man ihm zu essen gibt?',
    answer: 'Feurige Kohlen',
    accept: [['*kohle'], ['*glut']],
    bluffs: ['Asche der Reue', 'Tau des Himmels', 'Salz und Öl'],
    ref: 'Römer 12,20-21',
    discovery: 'Ein Bild aus Sprüche 25: Güte kann den Feind beschämen und verändern. Paulus folgert: Überwinde das Böse mit Gutem.',
  },
  {
    id: 'roem-kuss',
    book: 'Römer',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Womit sollen sich die Christen in Rom laut Paulus grüßen?',
    answer: 'Mit dem heiligen Kuss',
    accept: [['*kuss'], ['*kuess']],
    bluffs: ['Mit dem Friedensgruß Schalom', 'Mit einer tiefen Verbeugung', 'Mit erhobener rechter Hand'],
    ref: 'Römer 16,16',
    discovery: 'Den heiligen Kuss als Zeichen der Gemeinschaft empfiehlt Paulus gleich viermal in seinen Briefen.',
  },

  // ───────────── 1. Korinther ─────────────
  {
    id: '1kor-chloe',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Durch wessen Leute erfuhr Paulus von den Spaltungen in Korinth?',
    answer: 'Durch die Leute der Chloë',
    accept: [['chlo']],
    bluffs: ['Durch die Schüler des Apollos', 'Durch die Familie des Krispus', 'Durch Gajus und seine Hausgemeinde'],
    ref: '1. Korinther 1,11',
    discovery: 'Paulus nennt seine Quelle offen, statt anonyme Gerüchte weiterzugeben.',
  },
  {
    id: '1kor-parteien',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Nach welchen Namen nannten sich die streitenden Gruppen in Korinth?',
    answer: 'Paulus, Apollos, Kephas und Christus',
    accept: [['apollo'], ['kephas']],
    bluffs: ['Jakobus, Barnabas und Johannes', 'Mose, Elia und David', 'Silas, Timotheus und Titus'],
    ref: '1. Korinther 1,10-13',
    discovery: 'Paulus fragt zurück: Ist Christus etwa zerteilt? Kein Leiter darf zum Mittelpunkt einer Partei werden.',
  },
  {
    id: '1kor-500',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wie vielen Menschen erschien der Auferstandene laut 1. Korinther 15 auf einmal?',
    answer: 'Mehr als 500',
    accept: [['=500'], ['fuenfhundert']],
    bluffs: ['Mehr als 70', 'Etwa 120', 'Über 1000'],
    ref: '1. Korinther 15,3-8',
    discovery: 'Die meisten leben noch, schreibt Paulus. Man konnte sie also selbst fragen.',
    number: true,
  },
  {
    id: '1kor-ochse',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Welches Tier zitiert Paulus, um zu begründen, dass Verkündiger versorgt werden dürfen?',
    answer: 'Den Ochsen, der drischt',
    accept: [['ochs'], ['rind'], ['*drisch']],
    bluffs: ['Den Esel, der Lasten trägt', 'Das Schaf, das seinen Hirten kennt', 'Den Hund unter dem Tisch'],
    ref: '1. Korinther 9,9-15',
    discovery: 'Paulus zitiert 5. Mose 25,4 – und verzichtet danach selbst bewusst auf dieses Recht.',
  },
  {
    id: '1kor-hohelied',
    book: '1. Korinther',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Für welche Situation schrieb Paulus das berühmte Hohelied der Liebe zuerst?',
    answer: 'Für den Streit um Geistesgaben in der Gemeinde',
    accept: [['*gabe'], ['charism']],
    bluffs: ['Für die Hochzeit von Priszilla und Aquila', 'Für den Abschied von Ephesus', 'Für eine Taufe am Meer'],
    ref: '1. Korinther 12-14',
    discovery: 'Kapitel 13 steht zwischen zwei Kapiteln über Gaben: Ohne Liebe sind selbst die eindrucksvollsten Gaben wertlos.',
  },

  // ───────────── 2. Korinther ─────────────
  {
    id: '2kor-pfahl',
    book: '2. Korinther',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wie oft bat Paulus Gott, den „Pfahl im Fleisch“ von ihm zu nehmen?',
    answer: 'Dreimal',
    accept: [['=dreimal'], ['=drei'], ['=3'], ['=3x']],
    bluffs: ['Siebenmal', 'Jeden Tag', 'Vierzig Tage lang'],
    ref: '2. Korinther 12,7-9',
    discovery: 'Die Antwort war: Meine Gnade genügt dir. Was der Pfahl war, bleibt bis heute offen.',
    number: true,
  },
  {
    id: '2kor-see',
    book: '2. Korinther',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Wie lange trieb Paulus nach eigener Aussage einmal auf offener See?',
    answer: 'Einen Tag und eine Nacht',
    accept: [['=tag', 'nacht'], ['=24']],
    bluffs: ['Drei Tage und drei Nächte', 'Eine ganze Woche', 'Vierzig Stunden'],
    ref: '2. Korinther 11,23-30',
    discovery: 'Paulus zählt seine Leiden nicht auf, um zu prahlen. Er zeigt, wie Gottes Kraft in Schwachheit wirkt.',
  },
  {
    id: '2kor-schatz',
    book: '2. Korinther',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Worin tragen wir laut Paulus den Schatz des Evangeliums?',
    answer: 'In zerbrechlichen Tongefäßen',
    accept: [['*gefaess'], ['*gefaes'], ['=ton'], ['*tonge'], ['*krug'], ['*kruege'], ['*irden']],
    bluffs: ['In versiegelten Schriftrollen', 'In einer goldenen Lade', 'In Herzen aus Stein'],
    ref: '2. Korinther 4,7',
    discovery: 'Die Zerbrechlichkeit ist Absicht: So wird sichtbar, dass die Kraft von Gott kommt und nicht von uns.',
  },
  {
    id: '2kor-geber',
    book: '2. Korinther',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Was für einen Geber liebt Gott laut Paulus?',
    answer: 'Einen fröhlichen Geber',
    accept: [['froeh'], ['*freud'], ['=gern'], ['=gerne'], ['heiter']],
    bluffs: ['Einen verschwiegenen Geber', 'Einen demütigen Geber', 'Einen pünktlichen Geber'],
    ref: '2. Korinther 9,6-7',
    discovery: 'Paulus sammelte für die Armen in Jerusalem – aber ohne Druck: Großzügigkeit soll freiwillig geschehen.',
  },

  // ───────────── Galater ─────────────
  {
    id: 'gal-petrus',
    book: 'Galater',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wem widersprach Paulus in Antiochia offen ins Gesicht?',
    answer: 'Petrus',
    variants: ['Kephas'],
    accept: [['petrus'], ['kephas'], ['simon']],
    bluffs: ['Jakobus, dem Bruder Jesu', 'Johannes Markus', 'Apollos'],
    ref: 'Galater 2,11-14',
    discovery: 'Petrus hatte sich von den Mahlzeiten mit nichtjüdischen Christen zurückgezogen. Für Paulus stand die Wahrheit des Evangeliums auf dem Spiel.',
  },
  {
    id: 'gal-buchstaben',
    book: 'Galater',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Worauf weist Paulus am Ende des Galaterbriefs hin, als er selbst zur Feder greift?',
    answer: 'Auf seine großen Buchstaben',
    accept: [['*buchstab'], ['*schrift'], ['*letter']],
    bluffs: ['Auf seine zitternden Hände', 'Auf die Tränenflecken auf dem Papyrus', 'Auf das Siegel seines Rings'],
    ref: 'Galater 6,11',
    discovery: 'Ob schlechte Augen oder Nachdruck: Sicher ist nur, dass Paulus hier eigenhändig schreibt – und es ist ihm ernst.',
  },
  {
    id: 'gal-frucht',
    book: 'Galater',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wie viele Eigenschaften zählt Paulus zur „Frucht des Geistes“?',
    answer: 'Neun',
    accept: [['=neun'], ['=9']],
    bluffs: ['Sieben', 'Zwölf', 'Zehn'],
    ref: 'Galater 5,22-23',
    discovery: 'Liebe, Freude, Friede, Geduld, Freundlichkeit, Güte, Treue, Sanftmut, Selbstbeherrschung. „Frucht“ steht in der Einzahl: Sie wächst als Ganzes.',
    number: true,
  },
  {
    id: 'gal-430',
    book: 'Galater',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Wie viele Jahre nach der Zusage an Abraham kam laut Paulus das Gesetz?',
    answer: '430 Jahre',
    accept: [['=430'], ['vierhundertdreissig']],
    bluffs: ['400 Jahre', '40 Jahre', '490 Jahre'],
    ref: 'Galater 3,15-18',
    discovery: 'Paulus’ Punkt: Ein später gegebenes Gesetz kann Gottes frühere Zusage nicht außer Kraft setzen.',
    number: true,
  },

  // ───────────── Epheser ─────────────
  {
    id: 'eph-schwert',
    book: 'Epheser',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Was ist in der Waffenrüstung Gottes das „Schwert des Geistes“?',
    answer: 'Das Wort Gottes',
    accept: [['=wort'], ['*bibel'], ['*schrift']],
    bluffs: ['Das Gebet in Sprachen', 'Der Glaube an die Auferstehung', 'Die Liebe zum Nächsten'],
    ref: 'Epheser 6,10-17',
    discovery: 'Fast die ganze Rüstung dient dem Schutz. Und der Kampf richtet sich ausdrücklich nicht gegen Menschen (6,12).',
  },
  {
    id: 'eph-tychikus',
    book: 'Epheser',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Wer überbrachte den Epheserbrief und Nachrichten über Paulus?',
    answer: 'Tychikus',
    accept: [['tychik'], ['tichik'], ['tychic']],
    bluffs: ['Epaphras', 'Onesiphorus', 'Silas'],
    ref: 'Epheser 6,21-22',
    discovery: 'Tychikus ist auch im Kolosserbrief der Bote: ein treuer, oft übersehener Mitarbeiter (Kolosser 4,7).',
  },
  {
    id: 'eph-adresse',
    book: 'Epheser',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Welche Worte fehlen in einigen frühen Handschriften gleich im ersten Vers des Epheserbriefs?',
    answer: 'In Ephesus',
    accept: [['ephes']],
    bluffs: ['Und Timotheus', 'Apostel Jesu Christi', 'Gnade und Friede'],
    ref: 'Epheser 1,1',
    discovery: 'Darum halten viele den Brief für ein Rundschreiben an mehrere Gemeinden in Kleinasien.',
  },
  {
    id: 'eph-sonne',
    book: 'Epheser',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Was soll laut Epheser 4 nicht über eurem Zorn untergehen?',
    answer: 'Die Sonne',
    accept: [['sonne']],
    bluffs: ['Der Friede Gottes', 'Die Hoffnung', 'Das Licht der Lampe'],
    ref: 'Epheser 4,26-27',
    discovery: 'Zorn wird nicht einfach verboten. Aber er soll nicht über Nacht zur Bitterkeit werden.',
  },

  // ───────────── Philipper ─────────────
  {
    id: 'phil-evodia',
    book: 'Philipper',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Welche zwei Frauen bittet Paulus im Philipperbrief, sich zu versöhnen?',
    answer: 'Evodia und Syntyche',
    accept: [['evod'], ['synty']],
    bluffs: ['Lydia und Damaris', 'Maria und Martha', 'Priszilla und Phöbe'],
    ref: 'Philipper 4,2-3',
    discovery: 'Paulus nennt beide Mitkämpferinnen für das Evangelium. Ein Streit macht ihren Dienst nicht wertlos.',
  },
  {
    id: 'phil-epaphroditus',
    book: 'Philipper',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was passierte Epaphroditus, als er Paulus die Gaben aus Philippi brachte?',
    answer: 'Er wurde todkrank',
    accept: [['*krank'], ['*tod'], ['sterb'], ['starb']],
    bluffs: ['Er wurde selbst verhaftet', 'Er erlitt Schiffbruch', 'Er wurde unterwegs ausgeraubt'],
    ref: 'Philipper 2,25-30',
    discovery: 'Gott erbarmte sich über ihn, schreibt Paulus – und schickt ihn mit dem Brief nach Hause zurück.',
  },
  {
    id: 'phil-buergerrecht',
    book: 'Philipper',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was haben die Christen in Philippi laut Paulus im Himmel?',
    answer: 'Ihr Bürgerrecht',
    accept: [['*buerger'], ['heimat']],
    bluffs: ['Ihr eigenes Siegel', 'Ihre Namen in goldener Schrift', 'Einen reservierten Ehrenplatz'],
    ref: 'Philipper 3,20',
    discovery: 'Philippi war stolze römische Kolonie. Paulus sagt: Eure eigentliche Zugehörigkeit liegt bei Christus.',
  },
  {
    id: 'phil-vermag',
    book: 'Philipper',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Worum geht es, wenn Paulus schreibt: Ich vermag alles durch Christus?',
    answer: 'Mit Mangel und Überfluss leben können',
    accept: [['mangel'], ['ueberfl'], ['hunger'], ['satt'], ['*genueg'], ['zufried']],
    bluffs: ['Einen Wettlauf gewinnen', 'Kranke im Namen Jesu heilen', 'Einen Schiffbruch überleben'],
    ref: 'Philipper 4,11-13',
    discovery: 'Der berühmte Vers ist kein Erfolgsversprechen: Paulus hat gelernt, in jeder Lage zufrieden zu sein.',
  },

  // ───────────── Kolosser ─────────────
  {
    id: 'kol-laodizea',
    book: 'Kolosser',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Mit welcher Gemeinde sollen die Kolosser ihren Brief austauschen?',
    answer: 'Mit der Gemeinde in Laodizea',
    accept: [['laodi']],
    bluffs: ['Mit der Gemeinde in Ephesus', 'Mit der Gemeinde in Philippi', 'Mit der Gemeinde in Thessalonich'],
    ref: 'Kolosser 4,16',
    discovery: 'Briefe wurden vorgelesen und weitergegeben. Welcher Brief nach Laodizea gemeint ist, lässt sich nicht sicher sagen.',
  },
  {
    id: 'kol-arzt',
    book: 'Kolosser',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wie nennt Paulus seinen Begleiter Lukas im Kolosserbrief?',
    answer: 'Den geliebten Arzt',
    accept: [['*arzt'], ['mediz'], ['heiler']],
    bluffs: ['Den treuen Schreiber', 'Den mutigen Seefahrer', 'Den Erzähler der Gemeinde'],
    ref: 'Kolosser 4,14',
    discovery: 'Daher stammt die Überlieferung, dass der Evangelist Lukas Arzt war.',
  },
  {
    id: 'kol-onesimus',
    book: 'Kolosser',
    group: 'paulus',
    difficulty: 3,
    prompt: 'Wen schickt Paulus zusammen mit Tychikus nach Kolossä?',
    answer: 'Onesimus',
    accept: [['onesim']],
    bluffs: ['Titus', 'Silas', 'Apollos'],
    ref: 'Kolosser 4,7-9',
    discovery: 'Es ist derselbe Onesimus, für den Paulus im Philemonbrief bittet. Die beiden Briefe gehören zusammen.',
  },

  // ───────────── 1. Thessalonicher ─────────────
  {
    id: '1thess-sabbate',
    book: '1. Thessalonicher',
    group: 'paulus',
    difficulty: 3,
    prompt: 'An wie vielen Sabbaten predigte Paulus in der Synagoge von Thessalonich?',
    answer: 'An drei Sabbaten',
    accept: [['=drei'], ['=3']],
    bluffs: ['An sieben Sabbaten', 'An zwölf Sabbaten', 'An einem einzigen Sabbat'],
    ref: 'Apostelgeschichte 17,1-10',
    discovery: 'Wie lange er insgesamt blieb, ist damit nicht sicher. Doch die junge Gemeinde musste er früh verlassen.',
    number: true,
  },
  {
    id: '1thess-eltern',
    book: '1. Thessalonicher',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Mit wem vergleicht Paulus sich und seinen Dienst in Thessalonich?',
    answer: 'Mit einer Mutter und einem Vater',
    accept: [['mutter'], ['vater'], ['amme'], ['eltern']],
    bluffs: ['Mit einem Hirten und einem Wächter', 'Mit einem Bauern und einem Gärtner', 'Mit einem Lehrer und einem Richter'],
    ref: '1. Thessalonicher 2,7-12',
    discovery: 'Zärtlich wie eine Mutter, ermutigend wie ein Vater: So beschreibt Paulus seine Liebe zur jungen Gemeinde.',
  },
  {
    id: '1thess-haende',
    book: '1. Thessalonicher',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was sollen die Thessalonicher laut Paulus mit ihren eigenen Händen tun?',
    answer: 'Arbeiten',
    accept: [['arbeit'], ['schaff'], ['*werk']],
    bluffs: ['Dem Nachbarn Brot backen', 'Sie zum Gebet erheben', 'Kranken die Hände auflegen'],
    ref: '1. Thessalonicher 4,11-12',
    discovery: 'Alltag und Erwartung Jesu sind keine Gegensätze: Wer auf ihn wartet, lebt verlässlich.',
  },
  {
    id: '1thess-beten',
    book: '1. Thessalonicher',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Wie oft sollen Christen laut 1. Thessalonicher 5 beten?',
    answer: 'Ohne Unterlass',
    accept: [['*unterlass'], ['immer'], ['staendig'], ['ununterbroch'], ['allezeit'], ['jederzeit'], ['dauernd'], ['unaufhoerl'], ['pausenlos']],
    bluffs: ['Siebenmal am Tag', 'Morgens, mittags und abends', 'Vor jeder Mahlzeit'],
    ref: '1. Thessalonicher 5,16-18',
    discovery: 'Gemeint ist eine Haltung: im Gespräch mit Gott bleiben – fröhlich und dankbar in allem.',
  },

  // ───────────── 2. Thessalonicher ─────────────
  {
    id: '2thess-essen',
    book: '2. Thessalonicher',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Wer soll laut 2. Thessalonicher 3 auch nicht essen?',
    answer: 'Wer nicht arbeiten will',
    accept: [['arbeit']],
    bluffs: ['Wer am Sabbat kocht', 'Wer den Armen nichts abgibt', 'Wer ohne Dankgebet zu Tisch geht'],
    ref: '2. Thessalonicher 3,6-13',
    discovery: 'Gemeint sind Menschen, die nicht arbeiten wollen – nicht Kranke oder unverschuldet Arbeitslose.',
  },
  {
    id: '2thess-gruss',
    book: '2. Thessalonicher',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Woran sollen die Thessalonicher einen echten Brief von Paulus erkennen?',
    answer: 'An seinem eigenhändigen Gruß',
    accept: [['*haend'], ['*hand'], ['*unterschr'], ['*gruss'], ['*signatur']],
    bluffs: ['An einem Siegel mit Fischsymbol', 'An einem Gebet auf Hebräisch', 'Am Namen Jesu in der ersten Zeile'],
    ref: '2. Thessalonicher 3,17',
    discovery: 'Offenbar kursierten Aussagen, die sich auf angebliche Paulusbriefe beriefen (2,2). Deshalb das Echtheitszeichen.',
  },
  {
    id: '2thess-tag',
    book: '2. Thessalonicher',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Welche Behauptung brachte die Gemeinde in Thessalonich durcheinander?',
    answer: 'Der Tag des Herrn sei schon da',
    accept: [['=schon'], ['bereits'], ['angebroch'], ['gekommen'], ['eingetroffen']],
    bluffs: ['Paulus sei im Gefängnis gestorben', 'Die Taufe müsse wiederholt werden', 'Nur Juden dürften Abendmahl feiern'],
    ref: '2. Thessalonicher 2,1-3',
    discovery: 'Paulus beruhigt: Lasst euch nicht so schnell erschüttern. Christus behält das letzte Wort.',
  },

  // ───────────── 1. Timotheus ─────────────
  {
    id: '1tim-lystra',
    book: '1. Timotheus',
    group: 'pastoral',
    difficulty: 3,
    prompt: 'Aus welcher Stadt stammte Timotheus?',
    answer: 'Aus Lystra',
    accept: [['lystr']],
    bluffs: ['Aus Tarsus', 'Aus Philippi', 'Aus Kolossä'],
    ref: 'Apostelgeschichte 16,1-3',
    discovery: 'Seine Mutter war gläubige Jüdin, sein Vater Grieche. Timotheus verband zwei Welten.',
  },
  {
    id: '1tim-wein',
    book: '1. Timotheus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Welchen Gesundheitstipp gibt Paulus Timotheus?',
    answer: 'Etwas Wein für den Magen trinken',
    accept: [['wein'], ['magen']],
    bluffs: ['Morgens Honig mit Öl nehmen', 'Jeden Tag eine Stunde wandern', 'Nach Sonnenuntergang nichts mehr essen'],
    ref: '1. Timotheus 5,23',
    discovery: 'Ein überraschend persönlicher Satz mitten in Gemeinderegeln: Paulus sorgt sich um Timotheus’ häufige Krankheiten.',
  },
  {
    id: '1tim-jugend',
    book: '1. Timotheus',
    group: 'pastoral',
    difficulty: 1,
    prompt: 'Weswegen soll niemand Timotheus verachten?',
    answer: 'Wegen seiner Jugend',
    accept: [['jung'], ['jugend'], ['*alter']],
    bluffs: ['Wegen seiner griechischen Herkunft', 'Wegen seiner Schüchternheit', 'Wegen seiner leisen Stimme'],
    ref: '1. Timotheus 4,12',
    discovery: 'Statt sich zu rechtfertigen, soll er Vorbild sein: in Wort, Verhalten, Liebe, Glauben und Reinheit.',
  },
  {
    id: '1tim-geld',
    book: '1. Timotheus',
    group: 'pastoral',
    difficulty: 1,
    prompt: 'Was nennt Paulus eine Wurzel allen Übels?',
    answer: 'Die Geldliebe',
    accept: [['*geld'], ['*gier'], ['habsucht'], ['mammon'], ['reichtum']],
    bluffs: ['Den Neid', 'Den Stolz', 'Die Faulheit'],
    ref: '1. Timotheus 6,6-10',
    discovery: 'Nicht das Geld selbst ist das Problem, sondern die Liebe zu ihm. Genügsamkeit mit Gottvertrauen ist großer Gewinn.',
  },

  // ───────────── 2. Timotheus ─────────────
  {
    id: '2tim-mantel',
    book: '2. Timotheus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Was sollte Timotheus Paulus mitbringen?',
    answer: 'Einen Mantel, Bücher und Pergamente',
    accept: [['mantel'], ['pergament'], ['*buecher'], ['=buch'], ['*umhang']],
    bluffs: ['Brot, Öl und neue Sandalen', 'Eine Liste der Gemeindeleiter und einen Geldbeutel', 'Schreibtafeln, Wein und einen Reisegefährten'],
    ref: '2. Timotheus 4,13',
    discovery: 'Auch Paulus brauchte warme Kleidung und Lesestoff. Den Mantel hatte er in Troas bei Karpus gelassen.',
  },
  {
    id: '2tim-familie',
    book: '2. Timotheus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Wie hießen die Großmutter und die Mutter von Timotheus?',
    answer: 'Lois und Eunike',
    accept: [['lois'], ['eunik'], ['eunic']],
    bluffs: ['Junia und Tryphäna', 'Damaris und Chloë', 'Hanna und Susanna'],
    ref: '2. Timotheus 1,5',
    discovery: 'Der Glaube wurde in dieser Familie über Generationen weitergegeben: von der Großmutter zur Mutter zum Sohn.',
  },
  {
    id: '2tim-bilder',
    book: '2. Timotheus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Mit welchen drei Bildern beschreibt Paulus treuen Dienst in 2. Timotheus 2?',
    answer: 'Soldat, Wettkämpfer und Bauer',
    accept: [['soldat'], ['*bauer'], ['*kaempf'], ['sportl'], ['athlet'], ['*landwirt'], ['krieger'], ['*laeufer']],
    bluffs: ['Hirte, Fischer und Zimmermann', 'Lehrer, Arzt und Richter', 'Händler, Schreiber und Seemann'],
    ref: '2. Timotheus 2,3-7',
    discovery: 'Hingabe, Einsatz nach den Regeln und Geduld: Glaube braucht Ausdauer wie ein Beruf.',
  },
  {
    id: '2tim-demas',
    book: '2. Timotheus',
    group: 'pastoral',
    difficulty: 3,
    prompt: 'Wer hat Paulus verlassen, weil er „diese Welt lieb gewonnen“ hatte?',
    answer: 'Demas',
    accept: [['demas']],
    bluffs: ['Silas', 'Apollos', 'Aristarch'],
    ref: '2. Timotheus 4,9-11',
    discovery: 'Paulus nennt auch Treue: Nur Lukas ist bei mir. Und Markus, mit dem es einst Streit gab, soll Timotheus mitbringen.',
  },

  // ───────────── Titus ─────────────
  {
    id: 'tit-kreta',
    book: 'Titus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Auf welcher Insel ließ Paulus Titus zurück, um Älteste einzusetzen?',
    answer: 'Auf Kreta',
    accept: [['kreta'], ['creta']],
    bluffs: ['Auf Zypern', 'Auf Malta', 'Auf Rhodos'],
    ref: 'Titus 1,5',
    discovery: 'Titus war Grieche. Dass er nicht beschnitten werden musste, wurde zum Beispiel für die Freiheit des Evangeliums (Galater 2,3).',
  },
  {
    id: 'tit-zitat',
    book: 'Titus',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Welches scharfe Zitat über die Kreter führt Paulus im Titusbrief an?',
    answer: 'Kreter sind immer Lügner und faule Bäuche',
    accept: [['*luegner'], ['*baeuch'], ['*bauch'], ['*luege']],
    bluffs: ['Kreter schwören beim Meer und brechen jeden Eid', 'Kreter fürchten weder Gott noch Sturm', 'Kreter verkaufen sogar ihren eigenen Schatten'],
    ref: 'Titus 1,12-13',
    discovery: 'Das Zitat stammt von einem kretischen Dichter und gehört zur antiken Polemik. Es rechtfertigt keine Vorurteile über Völker.',
  },
  {
    id: 'tit-winter',
    book: 'Titus',
    group: 'pastoral',
    difficulty: 3,
    prompt: 'Wo wollte Paulus laut Titusbrief den Winter verbringen?',
    answer: 'In Nikopolis',
    accept: [['nikopol']],
    bluffs: ['In Ephesus', 'In Troas', 'In Korinth'],
    ref: 'Titus 3,12',
    discovery: 'Mitten in der Mission plant Paulus auch Winterpausen und Treffen mit seinen Mitarbeitern.',
  },

  // ───────────── Philemon ─────────────
  {
    id: 'phlm-name',
    book: 'Philemon',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was bedeutet der Name Onesimus?',
    answer: 'Nützlich',
    accept: [['nuetz'], ['*nutz'], ['brauchbar']],
    bluffs: ['Der Treue', 'Geschenk Gottes', 'Der Wanderer'],
    ref: 'Philemon 10-11',
    discovery: 'Paulus spielt mit dem Namen: Früher war er dir unnütz, jetzt ist er dir und mir nützlich.',
  },
  {
    id: 'phlm-schulden',
    book: 'Philemon',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Was bietet Paulus Philemon für Onesimus an?',
    answer: 'Für mögliche Schulden selbst aufzukommen',
    accept: [['*schuld'], ['*zahl'], ['*ersetz'], ['*erstatt'], ['auf', '*kommen'], ['*haft']],
    bluffs: ['Ihm ein Jahr lang selbst zu dienen', 'Ihm eine Schriftrolle zu schenken', 'Für ihn im Tempel zu opfern'],
    ref: 'Philemon 17-19',
    discovery: 'Paulus stellt sogar einen eigenhändigen Schuldschein aus: Ich, Paulus, will es bezahlen.',
  },
  {
    id: 'phlm-haus',
    book: 'Philemon',
    group: 'paulus',
    difficulty: 1,
    prompt: 'Wo traf sich die Gemeinde, an die der Philemonbrief auch gerichtet ist?',
    answer: 'In Philemons Haus',
    accept: [['*haus'], ['heim'], ['wohnung']],
    bluffs: ['In einer Synagoge', 'Am Flussufer', 'In einer Werkstatt'],
    ref: 'Philemon 1-2',
    discovery: 'Selbst dieser sehr persönliche Brief geht auch an die Hausgemeinde. Versöhnung ist eine Gemeindesache.',
  },

  // ───────────── Hebräer ─────────────
  {
    id: 'hebr-melchisedek',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Welcher geheimnisvolle Priesterkönig aus dem 1. Buch Mose wird im Hebräerbrief mit Jesus verglichen?',
    answer: 'Melchisedek',
    accept: [['melchi'], ['melki']],
    bluffs: ['Jitro von Midian', 'Eli von Schilo', 'Abimelech von Gerar'],
    ref: 'Hebräer 7,1-3; 1. Mose 14,18-20',
    discovery: 'Er segnete Abraham und erhielt von ihm den Zehnten – lange bevor es Priester aus dem Stamm Levi gab.',
  },
  {
    id: 'hebr-engel',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Wen haben manche laut Hebräerbrief unwissentlich als Gäste beherbergt?',
    answer: 'Engel',
    accept: [['engel']],
    bluffs: ['Propheten', 'Könige', 'Apostel'],
    ref: 'Hebräer 13,2',
    discovery: 'Eine Anspielung auf Abraham und seine drei Gäste (1. Mose 18): Gastfreundschaft kann überraschende Begegnungen schenken.',
  },
  {
    id: 'hebr-verfasser',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wer hat den Hebräerbrief geschrieben?',
    answer: 'Das weiß man nicht',
    accept: [['unbekannt'], ['anonym'], ['ungewiss'], ['unklar'], ['=weiss', 'nicht'], ['=niemand'], ['=keiner'], ['nicht', 'bekannt'], ['nicht', 'genannt']],
    bluffs: ['Paulus aus Rom', 'Lukas, der Arzt', 'Apollos aus Alexandria'],
    ref: 'Hebräer 13,22-25',
    discovery: 'Paulus wird im Brief nicht genannt. Vermutungen reichen von Barnabas bis Apollos – im Mittelpunkt steht Jesus, der Hohepriester.',
  },
  {
    id: 'hebr-rahab',
    book: 'Hebräer',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Welche Frau aus Jericho steht im Hebräerbrief in der Liste der Glaubensvorbilder?',
    answer: 'Rahab',
    accept: [['rahab'], ['rachab']],
    bluffs: ['Debora', 'Jaël', 'Ruth'],
    ref: 'Hebräer 11,31',
    discovery: 'Auch Jakobus nennt Rahab als Beispiel tätigen Glaubens (Jakobus 2,25) – eine Ausländerin mit bewegter Vergangenheit.',
  },

  // ───────────── Jakobus ─────────────
  {
    id: 'jak-zunge',
    book: 'Jakobus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Mit welchen Bildern beschreibt Jakobus die Macht der Zunge?',
    answer: 'Zaumzeug, Schiffsruder und Feuer',
    accept: [['*zaum'], ['*ruder'], ['*steuer'], ['*feuer'], ['funke'], ['zuegel'], ['*gebiss']],
    bluffs: ['Schlüssel, Waage und Wind', 'Hammer, Meißel und Säge', 'Pfeil, Bogen und Köcher'],
    ref: 'Jakobus 3,1-12',
    discovery: 'Ein kleines Organ mit großer Wirkung: Jakobus verbindet Glauben und Alltag mit Bildern wie in den Sprüchen.',
  },
  {
    id: 'jak-spiegel',
    book: 'Jakobus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Womit vergleicht Jakobus jemanden, der Gottes Wort hört, aber nicht tut?',
    answer: 'Mit jemandem, der in den Spiegel schaut und sich gleich vergisst',
    accept: [['spiegel']],
    bluffs: ['Mit einem Bauern, der nie aussät', 'Mit einer Lampe ohne Öl', 'Mit einem Wanderer, der seine Karte verliert'],
    ref: 'Jakobus 1,22-25',
    discovery: 'Jakobus’ Brücke zur Bergpredigt: Hören und Tun gehören zusammen (Matthäus 7,24-27).',
  },
  {
    id: 'jak-elia',
    book: 'Jakobus',
    group: 'allgemein',
    difficulty: 3,
    prompt: 'Wie lange regnete es nicht, nachdem Elia laut Jakobus darum gebetet hatte?',
    answer: 'Drei Jahre und sechs Monate',
    accept: [['sechs', 'monat'], ['*halb'], ['dreieinhalb'], ['=3', '=5'], ['=42']],
    bluffs: ['Sieben Jahre', 'Vierzig Tage', 'Zwölf Monate'],
    ref: 'Jakobus 5,16-18',
    discovery: 'Elia war ein Mensch wie wir, betont Jakobus. Das Gebet eines Gerechten vermag viel.',
    number: true,
  },
  {
    id: 'jak-daemonen',
    book: 'Jakobus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wer glaubt laut Jakobus auch, dass es nur einen Gott gibt – und zittert?',
    answer: 'Die Dämonen',
    accept: [['daemon'], ['teufel'], ['*geister'], ['satan']],
    bluffs: ['Die Heiden in Rom', 'Die Pharisäer', 'Die Wellen des Meeres'],
    ref: 'Jakobus 2,14-19',
    discovery: 'Bloßes Für-wahr-Halten reicht nicht: Lebendiger Glaube zeigt sich im Handeln.',
  },

  // ───────────── 1. Petrus ─────────────
  {
    id: '1petr-babylon',
    book: '1. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Welche Stadt meint Petrus vermutlich, wenn er Grüße aus „Babylon“ schickt?',
    answer: 'Rom',
    accept: [['=rom'], ['=roma'], ['=rome']],
    bluffs: ['Jerusalem', 'Alexandria', 'Antiochia'],
    ref: '1. Petrus 5,13',
    discovery: '„Babylon“ war ein Deckname für die Weltmacht. Auch Markus lässt von dort grüßen.',
  },
  {
    id: '1petr-steine',
    book: '1. Petrus',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Als was sollen sich Glaubende laut Petrus zu einem geistlichen Haus aufbauen lassen?',
    answer: 'Als lebendige Steine',
    accept: [['*stein']],
    bluffs: ['Als starke Zedernbalken', 'Als helle Fenster', 'Als gebrannte Lehmziegel'],
    ref: '1. Petrus 2,4-5',
    discovery: 'Petrus, der „Fels“, sieht Jesus als lebendigen Eckstein und alle Glaubenden als Steine am selben Bau.',
  },
  {
    id: '1petr-hoffnung',
    book: '1. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wofür sollen Christen laut Petrus jederzeit Rede und Antwort stehen können?',
    answer: 'Für ihre Hoffnung',
    accept: [['hoff']],
    bluffs: ['Für ihre Sabbatruhe', 'Für jede ihrer Spenden', 'Für ihre Gaben'],
    ref: '1. Petrus 3,15-16',
    discovery: 'Und zwar mit Sanftmut und Respekt: Glaube darf erklärt werden, ohne andere zu bedrängen.',
  },
  {
    id: '1petr-arche',
    book: '1. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wie viele Menschen wurden laut Petrus in der Arche gerettet?',
    answer: 'Acht',
    accept: [['=acht'], ['=8']],
    bluffs: ['Zwölf', 'Sieben', 'Vierzig'],
    ref: '1. Petrus 3,20-21',
    discovery: 'Petrus sieht in der Rettung durch das Wasser ein Bild für die Taufe.',
    number: true,
  },

  // ───────────── 2. Petrus ─────────────
  {
    id: '2petr-tag',
    book: '2. Petrus',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Was ist laut 2. Petrus bei Gott wie tausend Jahre?',
    answer: 'Ein Tag',
    accept: [['=tag']],
    bluffs: ['Ein Atemzug', 'Ein Wimpernschlag', 'Eine Stunde Gebet'],
    ref: '2. Petrus 3,8-9',
    discovery: 'Kein Rechenschlüssel für Endzeitdaten: Gott ist geduldig und will, dass Menschen umkehren.',
  },
  {
    id: '2petr-verklaerung',
    book: '2. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'An welches Erlebnis erinnert Petrus als Augenzeuge der Herrlichkeit Jesu?',
    answer: 'An die Verklärung auf dem Berg',
    accept: [['verklaer'], ['=berg'], ['*verwandl']],
    bluffs: ['An den reichen Fischfang am See', 'An die Stillung des Sturms', 'An das Abendmahl im Obergemach'],
    ref: '2. Petrus 1,16-18',
    discovery: 'Wir sind keinen ausgedachten Geschichten gefolgt, betont Petrus. Wir haben seine Größe selbst gesehen.',
  },
  {
    id: '2petr-eselin',
    book: '2. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wer wies laut 2. Petrus den Propheten Bileam zurecht?',
    answer: 'Seine Eselin',
    accept: [['esel'], ['*eselin']],
    bluffs: ['Ein Rabe', 'Seine Frau', 'Ein Hirtenjunge'],
    ref: '2. Petrus 2,15-16',
    discovery: 'Ein stummes Lasttier redet mit Menschenstimme: ein drastisches Bild gegen Verkündiger, die aus Gier handeln (4. Mose 22).',
  },
  {
    id: '2petr-paulus',
    book: '2. Petrus',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Was sagt Petrus über die Briefe des Paulus?',
    answer: 'Manches darin ist schwer zu verstehen',
    accept: [['schwer'], ['schwierig'], ['kompliz'], ['unverstaendl']],
    bluffs: ['Sie sind zu lang für den Gottesdienst', 'Nur Älteste sollten sie lesen', 'Sie sind schöner als die Psalmen'],
    ref: '2. Petrus 3,15-16',
    discovery: 'Er stellt sie neben die übrigen Schriften – und warnt davor, sie zu verdrehen.',
  },

  // ───────────── 1. Johannes ─────────────
  {
    id: '1joh-licht',
    book: '1. Johannes',
    group: 'allgemein',
    difficulty: 1,
    prompt: 'Mit welchen drei Wörtern fasst 1. Johannes 1,5 die Botschaft zusammen?',
    answer: 'Gott ist Licht',
    accept: [['licht'], ['liebe']],
    bluffs: ['Gott ist Stille', 'Gott ist Weite', 'Gott ist Klang'],
    ref: '1. Johannes 1,5-9',
    discovery: 'Licht, Liebe und Leben ziehen sich wie eine Spirale durch den Brief. Wer Schuld bekennt, findet Vergebung.',
  },
  {
    id: '1joh-gewiss',
    book: '1. Johannes',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Was sollen die Leser laut 1. Johannes 5,13 sicher wissen?',
    answer: 'Dass sie ewiges Leben haben',
    accept: [['ewig']],
    bluffs: ['Dass Jesus noch zu ihren Lebzeiten kommt', 'Dass ihre Namen im Tempel stehen', 'Wann der Tag des Herrn kommt'],
    ref: '1. Johannes 5,11-13',
    discovery: 'Das Johannesevangelium führt zum Glauben (20,31), der Brief stärkt die Gewissheit der Glaubenden.',
  },
  {
    id: '1joh-antichrist',
    book: '1. Johannes',
    group: 'allgemein',
    difficulty: 3,
    prompt: 'In welchen biblischen Büchern kommt das Wort „Antichrist“ vor?',
    answer: 'Nur in den Johannesbriefen',
    accept: [['*johannesbrief'], ['brief', 'joh'], ['=1', 'joh'], ['=2', 'joh']],
    bluffs: ['Nur in der Offenbarung', 'Im Buch Daniel und in der Offenbarung', 'Im 2. Thessalonicherbrief'],
    ref: '1. Johannes 2,18-22; 2. Johannes 7',
    discovery: 'Die Offenbarung spricht von „Tieren“, nicht vom Antichrist. Johannes meint damit auch Menschen, die schon damals Jesus als Christus leugneten.',
  },

  // ───────────── 2. Johannes ─────────────
  {
    id: '2joh-herrin',
    book: '2. Johannes',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'An wen ist der 2. Johannesbrief gerichtet?',
    answer: 'An die auserwählte Herrin und ihre Kinder',
    accept: [['herrin'], ['*auserw'], ['dame']],
    bluffs: ['An den geliebten Gajus', 'An die Witwen in Ephesus', 'An die sieben Gemeinden'],
    ref: '2. Johannes 1',
    discovery: 'Gemeint ist wohl eine Gemeinde – vielleicht aber auch eine Frau mit Familie. Beide Deutungen werden begründet vertreten.',
  },
  {
    id: '2joh-tinte',
    book: '2. Johannes',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Warum schreibt der Älteste im 2. Johannesbrief nicht noch mehr?',
    answer: 'Er will lieber persönlich kommen und reden',
    accept: [['persoenl'], ['angesicht'], ['*besuch'], ['*reden'], ['*sprechen'], ['=mund'], ['kommen']],
    bluffs: ['Ihm ging der Papyrus aus', 'Seine Augen waren zu schwach', 'Der Bote wollte sofort aufbrechen'],
    ref: '2. Johannes 12',
    discovery: 'Auch damals galt: Manches bespricht man besser von Angesicht zu Angesicht – damit die Freude vollkommen wird.',
  },

  // ───────────── 3. Johannes ─────────────
  {
    id: '3joh-diotrephes',
    book: '3. Johannes',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Was wirft der Älteste dem Diotrephes vor?',
    answer: 'Er will in der Gemeinde immer der Erste sein',
    accept: [['=erste'], ['=erster'], ['vorrang'], ['*macht'], ['*herrsch'], ['*bestimm'], ['*fuehr'], ['*chef'], ['*boss']],
    bluffs: ['Er hat die Kollekte veruntreut', 'Er feierte heidnische Feste', 'Er predigte stundenlang'],
    ref: '3. Johannes 9-10',
    discovery: 'Diotrephes wies reisende Brüder ab und warf Helfende hinaus. Gajus dagegen öffnete seine Tür.',
  },
  {
    id: '3joh-demetrius',
    book: '3. Johannes',
    group: 'allgemein',
    difficulty: 3,
    prompt: 'Wer bekommt im 3. Johannesbrief ein gutes Zeugnis von allen?',
    answer: 'Demetrius',
    accept: [['demetri']],
    bluffs: ['Diotrephes', 'Tychikus', 'Stephanas'],
    ref: '3. Johannes 11-12',
    discovery: 'Drei Personen, drei Beispiele: Gajus unterstützt, Diotrephes blockiert, Demetrius wird empfohlen.',
  },

  // ───────────── Judas ─────────────
  {
    id: 'jud-michael',
    book: 'Judas',
    group: 'allgemein',
    difficulty: 3,
    prompt: 'Worum stritt der Erzengel Michael laut Judasbrief mit dem Teufel?',
    answer: 'Um den Leichnam des Mose',
    accept: [['mose'], ['*leich'], ['*koerper'], ['=leib']],
    bluffs: ['Um die Seele des Judas Iskariot', 'Um den Thron Davids', 'Um die Bundeslade'],
    ref: 'Judas 9',
    discovery: 'Die Szene steht nicht im Alten Testament. Selbst Michael lästerte nicht, sondern sagte: Der Herr strafe dich.',
  },
  {
    id: 'jud-henoch',
    book: 'Judas',
    group: 'allgemein',
    difficulty: 3,
    prompt: 'Aus welchem Buch außerhalb des protestantischen Kanons zitiert der Judasbrief?',
    answer: 'Aus dem 1. Henochbuch',
    accept: [['*henoch'], ['*enoch']],
    bluffs: ['Aus dem Buch Tobit', 'Aus den Psalmen Salomos', 'Aus dem Buch Judit'],
    ref: 'Judas 14-15',
    discovery: 'Das Zitat macht nicht das ganze Henochbuch zur Heiligen Schrift. Judas nutzt ein bekanntes Wort als Warnung.',
  },
  {
    id: 'jud-bruder',
    book: 'Judas',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Wie stellt sich der Verfasser des Judasbriefs vor?',
    answer: 'Als Diener Jesu und Bruder des Jakobus',
    accept: [['jakob']],
    bluffs: ['Als Apostel und Augenzeuge', 'Als Sohn des Zebedäus', 'Als Ältester in Jerusalem'],
    ref: 'Judas 1',
    discovery: 'Traditionell gilt er als Bruder Jesu. Trotzdem nennt er sich bescheiden nur „Diener“ Jesu.',
  },

  // ───────────── Offenbarung ─────────────
  {
    id: 'offb-patmos',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 1,
    prompt: 'Auf welcher Insel empfing Johannes die Offenbarung?',
    answer: 'Auf Patmos',
    accept: [['patmo']],
    bluffs: ['Auf Zypern', 'Auf Kreta', 'Auf Malta'],
    ref: 'Offenbarung 1,9',
    discovery: 'Er war dort „um des Wortes Gottes willen“ – wohl als Verbannter.',
  },
  {
    id: 'offb-lau',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Welche Gemeinde ist laut Offenbarung weder kalt noch heiß?',
    answer: 'Laodizea',
    accept: [['laodi']],
    bluffs: ['Sardes', 'Pergamon', 'Thyatira'],
    ref: 'Offenbarung 3,14-22',
    discovery: 'Die reiche Stadt hielt sich für bedürfnislos. Jesus steht trotzdem vor ihrer Tür und klopft an.',
  },
  {
    id: 'offb-selig',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Was verspricht die Offenbarung gleich zu Beginn denen, die sie vorlesen und hören?',
    answer: 'Sie werden selig gepriesen',
    accept: [['selig'], ['segen'], ['gesegnet'], ['*glueck']],
    bluffs: ['Sie werden den Tag der Wiederkunft kennen', 'Sie bleiben vor Krankheit bewahrt', 'Sie werden Engel sehen'],
    ref: 'Offenbarung 1,3',
    discovery: 'Das Buch will gelesen, gehört und bewahrt werden. Insgesamt enthält es sieben Seligpreisungen.',
  },
  {
    id: 'offb-blaetter',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Wozu dienen die Blätter am Baum des Lebens im neuen Jerusalem?',
    answer: 'Zur Heilung der Völker',
    accept: [['heilung'], ['heilen'], ['=heil'], ['gesund'], ['*heilt']],
    bluffs: ['Als Schatten für die Märtyrer', 'Als Siegerkranz für die Treuen', 'Zum Schreiben neuer Namen'],
    ref: 'Offenbarung 22,1-2',
    discovery: 'Der Baum des Lebens aus 1. Mose 2 kehrt zurück: Die Bibel endet, wie sie begann – im Garten bei Gott.',
  },
  {
    id: 'offb-meer',
    book: 'Offenbarung',
    group: 'prophetie',
    difficulty: 2,
    prompt: 'Was gibt es auf der neuen Erde laut Offenbarung 21,1 nicht mehr?',
    answer: 'Das Meer',
    accept: [['meer'], ['=see'], ['ozean']],
    bluffs: ['Die Berge', 'Die Wüsten', 'Den Winter'],
    ref: 'Offenbarung 21,1-5',
    discovery: 'In der Bildwelt der Bibel steht das Meer oft für Chaos und Bedrohung. Gottes neue Welt ist davon frei.',
  },

  // ───────────── Das NT im Zusammenhang ─────────────
  {
    id: 'nt-synoptisch',
    book: 'Die Evangelien',
    group: 'evangelien',
    difficulty: 2,
    prompt: 'Warum heißen Matthäus, Markus und Lukas „synoptische“ Evangelien?',
    answer: 'Weil man sie gut nebeneinander lesen kann',
    accept: [['nebeneinander'], ['parallel'], ['*zusammen'], ['*vergleich'], ['ueberblick']],
    bluffs: ['Weil sie in Synagogen vorgelesen wurden', 'Weil alle drei mit der Geburt Jesu beginnen', 'Weil sie von Augenzeugen diktiert wurden'],
    ref: 'Matthäus, Markus, Lukas',
    discovery: 'Griechisch „syn-opsis“ heißt Zusammenschau. Johannes geht einen ganz eigenen Weg.',
  },
  {
    id: 'nt-katholisch',
    book: 'Allgemeine Briefe',
    group: 'allgemein',
    difficulty: 2,
    prompt: 'Was bedeutet „katholisch“ bei den sieben „katholischen Briefen“?',
    answer: 'Allgemein',
    accept: [['allgemein'], ['universal'], ['weltweit'], ['=alle'], ['*umfass']],
    bluffs: ['Vom Papst bestätigt', 'Von Petrus gesammelt', 'Für Neubekehrte'],
    ref: 'Jakobus bis Judas',
    discovery: 'Gemeint sind Jakobus, 1./2. Petrus, 1.–3. Johannes und Judas. Kurios: 3. Johannes hat trotzdem einen namentlichen Empfänger.',
  },
  {
    id: 'nt-paulusbriefe',
    book: 'Paulusbriefe',
    group: 'paulus',
    difficulty: 2,
    prompt: 'Wie viele Briefe im Neuen Testament nennen Paulus als Absender?',
    answer: '13',
    accept: [['=13'], ['dreizehn']],
    bluffs: ['14', '12', '10'],
    ref: 'Römer bis Philemon',
    discovery: 'Der Hebräerbrief wurde früher oft dazugezählt – er nennt aber keinen Verfasser.',
    number: true,
  },
  {
    id: 'nt-pastoral',
    book: 'Pastoralbriefe',
    group: 'pastoral',
    difficulty: 2,
    prompt: 'Unter welchem Sammelnamen kennt man die Briefe an Timotheus und Titus?',
    answer: 'Pastoralbriefe',
    accept: [['pastoral'], ['*hirte']],
    bluffs: ['Reisebriefe', 'Gefangenschaftsbriefe', 'Ältestenbriefe'],
    ref: '1./2. Timotheus, Titus',
    discovery: '„Pastoral“ kommt von Pastor, Hirte: Es geht um den Hirtendienst in der Gemeinde.',
  },

  // ───────────── Altes Testament ─────────────
  {
    id: 'at-axt',
    book: '2. Könige',
    group: 'at',
    difficulty: 3,
    prompt: 'Welcher geliehene Gegenstand aus Eisen schwamm in der Erzählung von Elisa plötzlich auf dem Wasser?',
    answer: 'Der Kopf einer Axt',
    variants: ['Eine Axt', 'Ein Beil'],
    accept: [['*axt'], ['*beil'], ['*aexte']],
    bluffs: ['Ein Kochtopf aus Eisen', 'Eine Pflugschar', 'Ein Hufeisen'],
    ref: '2. Könige 6,1–7',
    discovery: 'Das Werkzeug war nur geliehen, für einen armen Prophetenschüler ein ernster Verlust. Elisa wirft ein Stück Holz ins Wasser, und das Eisen schwimmt: Gott kümmert sich auch um Alltagssorgen.',
  },
  {
    id: 'at-raben',
    book: '1. Könige',
    group: 'at',
    difficulty: 1,
    prompt: 'Welche Vögel brachten dem Propheten Elia am Bach Krit zu essen?',
    answer: 'Raben',
    accept: [['rabe'], ['*raben'], ['kraehe'], ['dohle']],
    bluffs: ['Tauben', 'Adler', 'Störche'],
    ref: '1. Könige 17,2–6',
    discovery: 'Morgens und abends Brot und Fleisch, gebracht ausgerechnet von Raben, die nach dem Gesetz als unrein galten (3. Mose 11,15). Gott versorgt Elia auf eine Weise, mit der niemand rechnet.',
  },
  {
    id: 'at-ziegenfelle',
    book: '1. Mose',
    group: 'at',
    difficulty: 2,
    prompt: 'Womit bedeckte Rebekka Jakobs Hände und Hals, damit er sich anfühlte wie sein Bruder Esau?',
    answer: 'Mit Fellen junger Ziegen',
    variants: ['Mit Ziegenfellen'],
    accept: [['*fell'], ['*boeckchen'], ['*boecklein'], ['*zicklein'], ['*pelz'], ['ziegenhaar'], ['ziegenhaut']],
    bluffs: ['Mit Schafwolle', 'Mit groben Leinentüchern', 'Mit Lehm und Asche'],
    ref: '1. Mose 27,1–29',
    discovery: 'Der blinde Isaak tastet und zweifelt: „Die Stimme ist Jakobs Stimme, aber die Hände sind Esaus Hände.“ Jahre später wird Jakob selbst betrogen: Mit dem Blut eines Ziegenbocks täuschen ihn seine Söhne über Josef (1. Mose 37,31–33).',
  },
  {
    id: 'at-loewenhonig',
    book: 'Richter',
    group: 'at',
    difficulty: 2,
    prompt: 'An welchem ungewöhnlichen Ort fand Simson Honig?',
    answer: 'Im Kadaver eines Löwen',
    variants: ['In einem toten Löwen'],
    accept: [['*loew'], ['*aas'], ['kadaver']],
    bluffs: ['In einem hohlen Baumstamm', 'Im Schädel eines Esels', 'In einer Felsspalte am Bach'],
    ref: 'Richter 14,5–14',
    discovery: 'Daraus machte Simson ein Rätsel für die Hochzeitsgäste: „Speise ging aus von dem Fresser und Süßigkeit von dem Starken.“ Viele Ausleger sehen darin ein erstes Zeichen, wie leichtfertig der Gottgeweihte mit seiner Berufung umging.',
  },
  {
    id: 'at-wahnsinn',
    book: '1. Samuel',
    group: 'at',
    difficulty: 3,
    prompt: 'Wie versuchte David, sich vor König Achisch von Gat zu schützen?',
    answer: 'Er stellte sich wahnsinnig',
    variants: ['Er täuschte Wahnsinn vor', 'Er spielte den Verrückten'],
    accept: [['*wahnsinn'], ['*verrueckt'], ['irr'], ['*irre'], ['geistesk'], ['*sabber'], ['*speichel'], ['*narr']],
    bluffs: ['Er verkleidete sich als Hirte', 'Er gab sich als Philister aus', 'Er versteckte sich in einer Höhle'],
    ref: '1. Samuel 21,11–16',
    discovery: 'Er kritzelte an die Tore und ließ Speichel in seinen Bart laufen. Achisch spottet: „Hab ich zu wenig Wahnsinnige?“ Psalm 34 erinnert in seiner Überschrift an diese Flucht und dankt Gott für die Rettung.',
  },
  {
    id: 'at-ziegel',
    book: 'Hesekiel',
    group: 'at',
    difficulty: 3,
    prompt: 'Worauf sollte der Prophet Hesekiel ein Bild der Stadt Jerusalem einritzen?',
    answer: 'Auf einen Ziegelstein',
    variants: ['Auf einen Ziegel'],
    accept: [['*ziegel'], ['backstein'], ['lehm'], ['*tontafel'], ['=ton']],
    bluffs: ['Auf eine Wachstafel', 'Auf ein Stück Leder', 'Auf die Stadtmauer'],
    ref: 'Hesekiel 4,1–3',
    discovery: 'Davor sollte er eine Belagerung im Kleinen aufbauen, mit Wall und Sturmböcken. Hesekiel predigt oft mit Zeichenhandlungen: Die Verbannten sollten sehen, was Jerusalem bevorstand.',
  },
  {
    id: 'at-mundschenk',
    book: 'Nehemia',
    group: 'at',
    difficulty: 2,
    prompt: 'Welches Amt hatte Nehemia am Hof des persischen Königs?',
    answer: 'Mundschenk',
    variants: ['Er war Mundschenk'],
    accept: [['*schenk'], ['vorkost'], ['weinkost']],
    bluffs: ['Oberster Schreiber', 'Schatzmeister', 'Hauptmann der Leibwache'],
    ref: 'Nehemia 1,11; 2,1–8',
    discovery: 'Ein Vertrauensposten nah am König. Als Artahsasta sein trauriges Gesicht bemerkt, betet Nehemia kurz und bittet dann, Jerusalems Mauern wieder aufbauen zu dürfen. Er bekommt sogar Geleitbriefe und Holz dazu.',
  },
  {
    id: 'at-wurm',
    book: 'Jona',
    group: 'at',
    difficulty: 2,
    prompt: 'Welches kleine Tier ließ die Pflanze verdorren, die Jona Schatten gab?',
    answer: 'Ein Wurm',
    variants: ['Würmer'],
    accept: [['*wurm'], ['*wuerm'], ['made'], ['raupe'], ['larve']],
    bluffs: ['Eine Heuschrecke', 'Eine Ameise', 'Ein Käfer'],
    ref: 'Jona 4,5–11',
    discovery: 'Jona trauert um eine Staude, die über Nacht wuchs und verging. Gott fragt zurück, ob ihm dann nicht Ninive leidtun soll, eine Stadt mit mehr als 120.000 Menschen. Mit dieser offenen Frage endet das Buch.',
  },
  {
    id: 'at-joch',
    book: 'Jeremia',
    group: 'at',
    difficulty: 3,
    prompt: 'Was sollte sich Jeremia als prophetisches Zeichen auf den Nacken legen?',
    answer: 'Ein Joch mit Stricken',
    variants: ['Ein Joch'],
    accept: [['*joch']],
    bluffs: ['Einen Mühlstein', 'Eine eiserne Kette', 'Einen Sack voll Asche'],
    ref: 'Jeremia 27,1–11; 28,10–14',
    discovery: 'Das Joch zeigte: Juda und die Nachbarvölker sollen sich Babel beugen. Der Prophet Hananja zerbrach es öffentlich, doch Gott ließ ausrichten: Statt des hölzernen kommt nun ein eisernes Joch.',
  },
];

const BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]));

export function getQuestion(id: string): Question {
  const q = BY_ID.get(id);
  if (!q) throw new Error(`Unbekannte Frage: ${id}`);
  return q;
}
